primary_region = "sjc"
kill_signal = "SIGTERM"
kill_timeout = "40s"

[build]
  dockerfile = "../../Dockerfile"
  build-target = "all-in-one"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/healthz"
    timeout = "5s"

[mounts]
  source = "tokkeeper_state"
  destination = "/state"
  initial_size = "1gb"
  snapshot_retention = 7

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
