version: 2
updates:
  - package-ecosystem: uv
    directories:
      - /
      - /packaging/airmux
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      python-major-dependencies:
        patterns:
          - '*'
        update-types:
          - major
        group-by: dependency-name
      python-security-dependencies:
        applies-to: security-updates
        patterns:
          - '*'
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-dependencies:
        patterns:
          - '*'
