# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SecretStr,
)


class ActivityOut(BaseModel):
    """
    One entry in the feed: what changed, who changed it, when. Never the snapshots themselves.

    id mirrors the column, which the sequence fills: nullable in the table, never null once read.
    """

    id: Annotated[int | None, Field(title="Id")]
    table_name: Annotated[str, Field(title="Table Name")]
    record_id: Annotated[str, Field(title="Record Id")]
    action: Annotated[str, Field(title="Action")]
    user_id: Annotated[str, Field(title="User Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]


class BundleOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    version: Annotated[int, Field(title="Version")]
    issued_at: Annotated[AwareDatetime, Field(title="Issued At")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    signing_key_id: Annotated[str, Field(title="Signing Key Id")]


class ClaimOut(BaseModel):
    claimed: Annotated[bool, Field(title="Claimed")]


class CliAuthApproveIn(BaseModel):
    user_code: Annotated[str, Field(title="User Code")]
    org_id: Annotated[UUID, Field(title="Org Id")]


class CliAuthApprovedOut(BaseModel):
    status: Annotated[Literal["approved"], Field(title="Status")]
    client_name: Annotated[str, Field(title="Client Name")]


class CliAuthPollIn(BaseModel):
    poll_secret: Annotated[str, Field(title="Poll Secret")]


class CliAuthPollOut(BaseModel):
    status: Annotated[Literal["pending", "complete"], Field(title="Status")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    token: Annotated[str | None, Field(title="Token")] = None
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    org_name: Annotated[str | None, Field(title="Org Name")] = None


class CliAuthRequestOut(BaseModel):
    client_name: Annotated[str, Field(title="Client Name")]
    requester: Annotated[str, Field(title="Requester")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]


class CliAuthStartIn(BaseModel):
    client_name: Annotated[
        str,
        Field(
            description="Where the CLI runs, e.g. the hostname; becomes the minted key's label",
            max_length=80,
            min_length=1,
            title="Client Name",
        ),
    ]


class CliAuthStartOut(BaseModel):
    user_code: Annotated[str, Field(title="User Code")]
    verification_url: Annotated[str, Field(title="Verification Url")]
    poll_secret: Annotated[str, Field(title="Poll Secret")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    expires_in_seconds: Annotated[int, Field(title="Expires In Seconds")]


class DataPlaneInstanceOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]
    version: Annotated[str, Field(title="Version")]
    bundle_id: Annotated[UUID | None, Field(title="Bundle Id")]
    address: Annotated[str | None, Field(title="Address")]
    status: Annotated[Literal["online", "offline"], Field(title="Status")]
    first_seen: Annotated[AwareDatetime, Field(title="First Seen")]
    last_seen: Annotated[AwareDatetime, Field(title="Last Seen")]


class DeletedOutUUID(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class DeletedOutStr(BaseModel):
    id: Annotated[str, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class EnvelopeBundleOut(BaseModel):
    data: BundleOut


class EnvelopeClaimOut(BaseModel):
    data: ClaimOut


class EnvelopeCliAuthApprovedOut(BaseModel):
    data: CliAuthApprovedOut


class EnvelopeCliAuthPollOut(BaseModel):
    data: CliAuthPollOut


class EnvelopeCliAuthRequestOut(BaseModel):
    data: CliAuthRequestOut


class EnvelopeCliAuthStartOut(BaseModel):
    data: CliAuthStartOut


class EnvelopeDeletedOutUUID(BaseModel):
    data: DeletedOutUUID


class EnvelopeDeletedOutStr(BaseModel):
    data: DeletedOutStr


class EnvelopeListActivityOut(BaseModel):
    data: Annotated[list[ActivityOut], Field(title="Data")]


class EnvelopeListBundleOut(BaseModel):
    data: Annotated[list[BundleOut], Field(title="Data")]


class EnvelopeListDataPlaneInstanceOut(BaseModel):
    data: Annotated[list[DataPlaneInstanceOut], Field(title="Data")]


class EventsIngestedOut(BaseModel):
    received: Annotated[int, Field(title="Received")]
    ingested: Annotated[int, Field(title="Ingested")]


class HeartbeatOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]


class HeartbeatV1(BaseModel):
    """
    A data plane announcing itself to the control plane; the record survives, liveness is derived from last_seen.

    A data plane registers against the instance: which bundle it happens to serve is
    config, and bundle_id already says which one that is.
    """

    instance_id: Annotated[UUID, Field(title="Instance Id")]
    version: Annotated[str, Field(title="Version")]
    bundle_id: Annotated[UUID | None, Field(title="Bundle Id")] = None


class InferenceKeyIn(BaseModel):
    label: Annotated[
        str,
        Field(
            description="What this key is for, e.g. staging or the calling app; shown in listings",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]


class InferenceKeyMintedOut(BaseModel):
    """
    The mint result: the id plus the one-time plaintext token, which is not a column and never returns again.
    """

    id: Annotated[UUID, Field(title="Id")]
    token: Annotated[str, Field(title="Token")]


class InferenceKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    revoked: Annotated[bool, Field(title="Revoked")]
    label: Annotated[str, Field(title="Label")]
    prefix: Annotated[str, Field(title="Prefix")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class InferenceKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]


class InstanceKeyMintedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    scopes: Annotated[list[str] | None, Field(title="Scopes")]
    label: Annotated[str, Field(title="Label")]
    token: Annotated[str, Field(title="Token")]


class InstanceKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    revoked: Annotated[bool, Field(title="Revoked")]
    scopes: Annotated[list[str] | None, Field(title="Scopes")]
    label: Annotated[str, Field(title="Label")]
    prefix: Annotated[str, Field(title="Prefix")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class InstanceKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]


class KeyEntry(BaseModel):
    """
    An API key as the data plane sees it: enough to authorize with zero I/O.

    The caller's bearer is an opaque secret; the data plane hashes it (see
    credentials.py) and looks the hash up here. Absence is invalidity, so
    revocation is simply dropping out of the next bundle. key_id exists for
    event attribution only. The bundle carries hashes of live secrets and
    stays org-sensitive even though the hashes are not reversible.
    """

    key_id: Annotated[str, Field(title="Key Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    token_hash: Annotated[str, Field(title="Token Hash")]


class LoginIn(BaseModel):
    email: Annotated[str, Field(title="Email")]
    password: Annotated[str, Field(title="Password")]


class ManagementKeyMintedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    scopes: Annotated[list[str] | None, Field(title="Scopes")]
    label: Annotated[str, Field(title="Label")]
    token: Annotated[str, Field(title="Token")]


class ManagementKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    revoked: Annotated[bool, Field(title="Revoked")]
    scopes: Annotated[list[str] | None, Field(title="Scopes")]
    label: Annotated[str, Field(title="Label")]
    prefix: Annotated[str, Field(title="Prefix")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class ManagementKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]


class MeOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    instance_admin: Annotated[bool, Field(title="Instance Admin")]
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class MembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    status: Annotated[Literal["member"], Field(title="Status")]


class ModelEntry(BaseModel):
    """
    A routable model: the caller-facing id plus how to reach and bill it.
    """

    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    upstream_model: Annotated[str, Field(title="Upstream Model")]
    input_price_per_mtok: Annotated[float, Field(title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[float, Field(title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[float, Field(title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[float, Field(title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(title="Context Window")]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")] = None
    capabilities: Annotated[list[str], Field(title="Capabilities")]


class ModelIn(BaseModel):
    model_id: Annotated[str, Field(description="Caller-facing model name", title="Model Id")]
    provider_id: Annotated[str, Field(description="Provider id the model routes to", title="Provider Id")]
    upstream_model: Annotated[
        str | None,
        Field(
            description="Model name sent to the provider, lets model_id be an alias; defaults to model_id",
            title="Upstream Model",
        ),
    ] = ""
    input_price_per_mtok: Annotated[
        float | None,
        Field(description="USD per million input tokens", title="Input Price Per Mtok"),
    ] = 0.0
    output_price_per_mtok: Annotated[
        float | None,
        Field(description="USD per million output tokens", title="Output Price Per Mtok"),
    ] = 0.0
    cache_read_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million cache-read input tokens",
            title="Cache Read Price Per Mtok",
        ),
    ] = 0.0
    cache_write_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million cache-write input tokens",
            title="Cache Write Price Per Mtok",
        ),
    ] = 0.0
    context_window: Annotated[
        int | None,
        Field(description="Context window in tokens", title="Context Window"),
    ] = 128000
    max_output_tokens: Annotated[
        int | None,
        Field(
            description="Max completion tokens; requests are clamped to it",
            title="Max Output Tokens",
        ),
    ] = None
    capabilities: Annotated[
        list[str] | None,
        Field(description="Capabilities, comma separated", title="Capabilities"),
    ] = ["streaming", "tools"]


class ModelOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    upstream_model: Annotated[str, Field(title="Upstream Model")]
    input_price_per_mtok: Annotated[float, Field(title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[float, Field(title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[float, Field(title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[float, Field(title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(title="Context Window")]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")]
    capabilities: Annotated[list[str], Field(title="Capabilities")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class OrgCreate(BaseModel):
    name: Annotated[str, Field(description="Org name, e.g. My Org", title="Name")]


class OrgMemberOut(BaseModel):
    """
    A member of the acting org: who they are and that they belong.

    Deliberately not UserOut: that carries the user's every membership, which would let one org's
    credential read the shape of the orgs it has no scope over.
    """

    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]
    status: Annotated[Literal["member"], Field(title="Status")]


class OrgOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    personal_for: Annotated[UUID | None, Field(title="Personal For")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class OrgUpdate(BaseModel):
    name: Annotated[str | None, Field(title="Name")] = None


class PasswordChangeIn(BaseModel):
    current_password: Annotated[str, Field(title="Current Password")]
    new_password: Annotated[str, Field(min_length=8, title="New Password")]


class PasswordChangedOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    status: Annotated[Literal["changed"], Field(title="Status")]


class ProviderCredentialIn(BaseModel):
    """
    Creating a credential is an action, not a plain row insert: the value crosses the wire once
    and is never a column, so this is not a RecordCreate and is exempt from parity by that choice.

    The value is a SecretStr so nothing that renders this model can print it. That is not enough on
    its own: the validation error handler in app.py drops the offending input, or a body that fails
    validation for some other reason comes back to the caller with the key still in it.
    """

    provider: Annotated[
        str,
        Field(description="Provider name from the catalog, e.g. openai", title="Provider"),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Handle for this key within the provider and scope, e.g. prod or backup",
            max_length=80,
            min_length=1,
            title="Name",
        ),
    ] = "default"
    value: Annotated[
        SecretStr,
        Field(
            description="The provider API key. Written to the secret store and never persisted anywhere else",
            title="Value",
        ),
    ]
    priority: Annotated[
        int | None,
        Field(description="Lower is tried first; ties break by name", title="Priority"),
    ] = 100
    workspace: Annotated[
        str | None,
        Field(
            description="Workspace id or slug for a workspace-scoped key; omitted makes it org-scoped",
            title="Workspace",
        ),
    ] = None


class ProviderCredentialOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    provider_name: Annotated[str, Field(title="Provider Name")]
    name: Annotated[str, Field(title="Name")]
    priority: Annotated[int, Field(title="Priority")]
    enabled: Annotated[bool, Field(title="Enabled")]
    version: Annotated[int, Field(title="Version")]
    status: Annotated[str, Field(title="Status")]
    status_at: Annotated[AwareDatetime | None, Field(title="Status At")]
    fingerprint: Annotated[str, Field(title="Fingerprint")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    scope: Annotated[Literal["platform", "org", "workspace"], Field(title="Scope")]


class ProviderCredentialUpdate(BaseModel):
    priority: Annotated[int | None, Field(title="Priority")] = None
    enabled: Annotated[bool | None, Field(title="Enabled")] = None


class ProviderCredentialValueIn(BaseModel):
    """
    A rotation: the same credential, a new value.
    """

    value: Annotated[SecretStr, Field(description="The replacement provider API key", title="Value")]


class ProviderEntry(BaseModel):
    """
    An upstream LLM provider endpoint, plus its profile: declarative facts about what the
    provider accepts, so onboarding quirks is a bundle edit rather than an adapter branch.
    Profile fields are names, sets and flags, never predicates; a provider that needs a
    predicate needs an adapter.
    """

    provider_id: Annotated[str, Field(title="Provider Id")]
    kind: Annotated[Literal["openai_compatible", "anthropic"], Field(title="Kind")]
    base_url: Annotated[AnyUrl, Field(title="Base Url")]
    param_aliases: Annotated[dict[str, str] | None, Field(title="Param Aliases")] = None
    accepted_params: Annotated[list[str] | None, Field(title="Accepted Params")] = None
    params_closed: Annotated[bool | None, Field(title="Params Closed")] = False


class ProviderIn(BaseModel):
    """
    How to reach a provider, not how to authenticate to it: credentials are their own resource.

    Extra keys are refused so a taxonomy still carrying credential_ref fails loudly. Ignoring it
    would leave the operator believing they configured a credential when the provider has none.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider_id: Annotated[str, Field(description="Provider name, e.g. openai", title="Provider Id")]
    kind: Annotated[
        Literal["openai_compatible", "anthropic"] | None,
        Field(description="Adapter kind", title="Kind"),
    ] = "openai_compatible"
    base_url: Annotated[
        str,
        Field(
            description="OpenAI-compatible endpoint, e.g. https://api.groq.com/openai/v1",
            title="Base Url",
        ),
    ]
    icon: Annotated[
        str | None,
        Field(
            description="Provider mark as a standalone 24x24 SVG document, empty when the provider has none. Carried as markup so adding a provider needs no client change to make it recognisable, which makes it untrusted markup to whatever renders it; sanitize at the render site",
            title="Icon",
        ),
    ] = ""
    param_aliases: Annotated[
        dict[str, str] | None,
        Field(
            description="Canonical param name to this provider's spelling",
            title="Param Aliases",
        ),
    ] = None
    accepted_params: Annotated[
        list[str] | None,
        Field(
            description="Params known accepted beyond the core; consulted when params_closed",
            title="Accepted Params",
        ),
    ] = None
    params_closed: Annotated[
        bool | None,
        Field(
            description="True when the provider's request schema rejects unknown params",
            title="Params Closed",
        ),
    ] = False


class ProviderOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    kind: Annotated[str, Field(title="Kind")]
    base_url: Annotated[str, Field(title="Base Url")]
    icon: Annotated[str, Field(title="Icon")]
    param_aliases: Annotated[dict[str, str], Field(title="Param Aliases")]
    accepted_params: Annotated[list[str] | None, Field(title="Accepted Params")]
    params_closed: Annotated[bool, Field(title="Params Closed")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class QuickstartIn(BaseModel):
    token: Annotated[str, Field(title="Token")]


class QuickstartOut(BaseModel):
    path: Annotated[str, Field(title="Path")]


class Scope(
    RootModel[
        Literal[
            "inference-keys:read",
            "inference-keys:write",
            "workspaces:read",
            "workspaces:create",
            "workspaces:write",
            "workspaces:delete",
            "bundles:read",
            "bundles:write",
            "events:read",
            "data-planes:read",
            "provider-credentials:read",
            "provider-credentials:write",
            "taxonomy:read",
            "taxonomy:write",
            "orgs:read",
            "orgs:create",
            "orgs:write",
            "orgs:delete",
            "users:read",
            "users:write",
            "activity:read",
            "management-keys:read",
            "management-keys:write",
            "instance-keys:read",
            "instance-keys:write",
            "sync",
        ]
    ]
):
    root: Annotated[
        Literal[
            "inference-keys:read",
            "inference-keys:write",
            "workspaces:read",
            "workspaces:create",
            "workspaces:write",
            "workspaces:delete",
            "bundles:read",
            "bundles:write",
            "events:read",
            "data-planes:read",
            "provider-credentials:read",
            "provider-credentials:write",
            "taxonomy:read",
            "taxonomy:write",
            "orgs:read",
            "orgs:create",
            "orgs:write",
            "orgs:delete",
            "users:read",
            "users:write",
            "activity:read",
            "management-keys:read",
            "management-keys:write",
            "instance-keys:read",
            "instance-keys:write",
            "sync",
        ],
        Field(
            description="What a management credential may do; org and instance row-scoping are a separate axis.\n\nA scope restricts the credential, never expands it: a token minted without scopes carries the\nowning user's full authority, an explicit list is a restriction that also excludes scopes\ninvented later. Roles arrive later as named bundles over these same values.\n\nOrgs and workspaces split their lifecycle three ways because founding a tenant and destroying\none with everything inside it are each a different privilege from governing one day to day:\n:create founds, :write governs, :delete destroys. Elsewhere :write still covers all three.",
            title="Scope",
        ),
    ]


class SecretPurpose(RootModel[Literal["provider"]]):
    root: Annotated[
        Literal["provider"],
        Field(
            description="What family a secret belongs to. Both planes must agree, which is why it lives here.\n\nA new purpose is one member, and every store keeps it apart from the others without changing.",
            title="SecretPurpose",
        ),
    ]


class SecretRef(BaseModel):
    """
    Which secret, said in terms of the domain rather than of any store's layout.

    purpose is the family, service is what inside that family the secret authenticates to (a
    provider name today), and name is the caller-facing handle that lets one service hold several.
    secret_id is what actually makes a ref unique; the rest is carried so a store with somewhere
    legible to put it can.

    org_id and workspace_id are absent for a platform secret and org_id alone is present for an org
    one, so the same two fields express all three scopes.
    """

    purpose: SecretPurpose
    service: Annotated[str, Field(title="Service")]
    name: Annotated[str, Field(title="Name")]
    secret_id: Annotated[UUID, Field(title="Secret Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")] = None


class ServiceAccountIn(BaseModel):
    name: Annotated[
        str,
        Field(
            description="Service account name; the email is derived as name-<id>@airbytesvcaccount.ai",
            title="Name",
        ),
    ]


class SignupIn(BaseModel):
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str | None, Field(title="Name")] = ""
    password: Annotated[str, Field(min_length=8, title="Password")]


class TaxonomyOut(BaseModel):
    providers: Annotated[list[ProviderOut], Field(title="Providers")]
    models: Annotated[list[ModelOut], Field(title="Models")]


class UsageEventOut(BaseModel):
    event_id: Annotated[UUID, Field(title="Event Id")]
    request_id: Annotated[UUID, Field(title="Request Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    key_id: Annotated[str, Field(title="Key Id")]
    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]
    cost_usd: Annotated[float, Field(title="Cost Usd")]
    cost_input_usd: Annotated[float, Field(title="Cost Input Usd")]
    cost_output_usd: Annotated[float, Field(title="Cost Output Usd")]
    cache_read_tokens: Annotated[int, Field(title="Cache Read Tokens")]
    cache_write_tokens: Annotated[int, Field(title="Cache Write Tokens")]
    latency_ms: Annotated[int, Field(title="Latency Ms")]
    status: Annotated[str, Field(title="Status")]
    stream: Annotated[bool, Field(title="Stream")]
    credential_id: Annotated[UUID | None, Field(title="Credential Id")]
    credential_scope: Annotated[str | None, Field(title="Credential Scope")]


class UsageEventV1(BaseModel):
    """
    One metered request, emitted by the data plane and ingested by the control plane.

    Delivery is at-least-once from a local disk buffer; the control plane upserts on
    event_id, so replays after an outage land exactly once.
    """

    schema_version: Annotated[Literal[1], Field(title="Schema Version")] = 1
    event_id: Annotated[UUID, Field(title="Event Id")]
    request_id: Annotated[UUID, Field(title="Request Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    key_id: Annotated[str, Field(title="Key Id")]
    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]
    cost_usd: Annotated[float, Field(title="Cost Usd")]
    cost_input_usd: Annotated[float | None, Field(title="Cost Input Usd")] = 0.0
    cost_output_usd: Annotated[float | None, Field(title="Cost Output Usd")] = 0.0
    cache_read_tokens: Annotated[int | None, Field(title="Cache Read Tokens")] = 0
    cache_write_tokens: Annotated[int | None, Field(title="Cache Write Tokens")] = 0
    latency_ms: Annotated[int, Field(title="Latency Ms")]
    status: Annotated[
        Literal[
            "ok",
            "upstream_error",
            "denied",
            "timeout",
            "cancelled",
            "credential_rejected",
            "rate_limited",
        ],
        Field(title="Status"),
    ]
    stream: Annotated[bool, Field(title="Stream")]
    credential_id: Annotated[UUID | None, Field(title="Credential Id")] = None
    credential_scope: Annotated[Literal["platform", "org", "workspace"] | None, Field(title="Credential Scope")] = None


class UserCreate(BaseModel):
    email: Annotated[str, Field(description="Unique email identifying the user", title="Email")]
    name: Annotated[
        str | None,
        Field(description="Display name, defaults to the email", title="Name"),
    ] = ""


class UserOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Any | None, Field(title="Input")] = None
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None


class WorkspaceCreate(BaseModel):
    name: Annotated[str, Field(description="Workspace name, e.g. Staging", title="Name")]
    slug: Annotated[
        str | None,
        Field(
            description="Workspace handle, unique in the org and usable in place of the id; derived from the name when omitted",
            max_length=63,
            pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$",
            title="Slug",
        ),
    ] = ""


class WorkspaceMembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    status: Annotated[Literal["member"], Field(title="Status")]


class WorkspaceOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    name: Annotated[str, Field(title="Name")]
    slug: Annotated[str, Field(title="Slug")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class WorkspaceUpdate(BaseModel):
    name: Annotated[str | None, Field(title="Name")] = None


class CredentialEntry(BaseModel):
    """
    One provider key the data plane may spend against, named but not carried.

    The ref says which secret; the data plane fetches the value from the store it is configured
    with. Nothing here is a secret and nothing here is a location, so a bundle at rest and a bundle
    on the wire are both safe to read.

    version is the cache key: a rotation keeps the ref and bumps this, so a data plane refetches
    within one poll rather than waiting out a TTL.
    """

    ref: SecretRef
    priority: Annotated[int, Field(title="Priority")]
    version: Annotated[int, Field(title="Version")]


class EnrollOut(BaseModel):
    orgs: Annotated[list[OrgOut], Field(title="Orgs")]
    personal_org_id: Annotated[UUID | None, Field(title="Personal Org Id")]


class EnvelopeEnrollOut(BaseModel):
    data: EnrollOut


class EnvelopeEventsIngestedOut(BaseModel):
    data: EventsIngestedOut


class EnvelopeHeartbeatOut(BaseModel):
    data: HeartbeatOut


class EnvelopeInferenceKeyMintedOut(BaseModel):
    data: InferenceKeyMintedOut


class EnvelopeInferenceKeyRevokedOut(BaseModel):
    data: InferenceKeyRevokedOut


class EnvelopeInstanceKeyMintedOut(BaseModel):
    data: InstanceKeyMintedOut


class EnvelopeInstanceKeyRevokedOut(BaseModel):
    data: InstanceKeyRevokedOut


class EnvelopeManagementKeyMintedOut(BaseModel):
    data: ManagementKeyMintedOut


class EnvelopeManagementKeyRevokedOut(BaseModel):
    data: ManagementKeyRevokedOut


class EnvelopeMeOut(BaseModel):
    data: MeOut


class EnvelopeMembershipOut(BaseModel):
    data: MembershipOut


class EnvelopeModelOut(BaseModel):
    data: ModelOut


class EnvelopeOrgOut(BaseModel):
    data: OrgOut


class EnvelopePasswordChangedOut(BaseModel):
    data: PasswordChangedOut


class EnvelopeProviderCredentialOut(BaseModel):
    data: ProviderCredentialOut


class EnvelopeProviderOut(BaseModel):
    data: ProviderOut


class EnvelopeQuickstartOut(BaseModel):
    data: QuickstartOut


class EnvelopeTaxonomyOut(BaseModel):
    data: TaxonomyOut


class EnvelopeUserOut(BaseModel):
    data: UserOut


class EnvelopeWorkspaceMembershipOut(BaseModel):
    data: WorkspaceMembershipOut


class EnvelopeWorkspaceOut(BaseModel):
    data: WorkspaceOut


class EnvelopeListInferenceKeyOut(BaseModel):
    data: Annotated[list[InferenceKeyOut], Field(title="Data")]


class EnvelopeListInstanceKeyOut(BaseModel):
    data: Annotated[list[InstanceKeyOut], Field(title="Data")]


class EnvelopeListManagementKeyOut(BaseModel):
    data: Annotated[list[ManagementKeyOut], Field(title="Data")]


class EnvelopeListOrgMemberOut(BaseModel):
    data: Annotated[list[OrgMemberOut], Field(title="Data")]


class EnvelopeListOrgOut(BaseModel):
    data: Annotated[list[OrgOut], Field(title="Data")]


class EnvelopeListProviderCredentialOut(BaseModel):
    data: Annotated[list[ProviderCredentialOut], Field(title="Data")]


class EnvelopeListUsageEventOut(BaseModel):
    data: Annotated[list[UsageEventOut], Field(title="Data")]


class EnvelopeListUserOut(BaseModel):
    data: Annotated[list[UserOut], Field(title="Data")]


class EnvelopeListWorkspaceMembershipOut(BaseModel):
    data: Annotated[list[WorkspaceMembershipOut], Field(title="Data")]


class EnvelopeListWorkspaceOut(BaseModel):
    data: Annotated[list[WorkspaceOut], Field(title="Data")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class InstanceKeyIn(BaseModel):
    label: Annotated[
        str,
        Field(
            description="Where this key lives, e.g. ci or a data plane; shown in listings",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]
    user_id: Annotated[
        UUID | None,
        Field(
            description="Instance admin the key is minted for; defaults to the acting user",
            title="User Id",
        ),
    ] = None
    scopes: Annotated[
        list[Scope] | None,
        Field(
            description="Restrict the key to these scopes; omit for the user's full authority",
            title="Scopes",
        ),
    ] = None


class ManagementKeyIn(BaseModel):
    label: Annotated[
        str,
        Field(
            description="Where this key lives, e.g. ci or laptop; shown in listings",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]
    user_id: Annotated[
        UUID | None,
        Field(
            description="User the key is minted for; defaults to the acting user",
            title="User Id",
        ),
    ] = None
    scopes: Annotated[
        list[Scope] | None,
        Field(
            description="Restrict the key to these scopes; omit for the user's full authority",
            title="Scopes",
        ),
    ] = None


class Catalog(BaseModel):
    """
    Everything routable in one org: providers, the models that point at them, and the credentials
    they are reached with.
    """

    providers: Annotated[list[ProviderEntry], Field(title="Providers")]
    models: Annotated[list[ModelEntry], Field(title="Models")]
    credentials: Annotated[list[CredentialEntry] | None, Field(title="Credentials", validate_default=True)] = []


class BundleV1(BaseModel):
    """
    The complete policy snapshot one data plane needs to serve requests with no database.

    Compiled by the control plane as a pure function of database state, signed, and polled
    by the data plane. If a feature seems to need a DB read on the request path, the bundle
    is missing a field; add the field here instead.
    """

    schema_version: Annotated[Literal[1], Field(title="Schema Version")] = 1
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    issued_at: Annotated[AwareDatetime, Field(title="Issued At")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    keys: Annotated[list[KeyEntry], Field(title="Keys")]
    catalog: Catalog


class SignedBundle(BaseModel):
    """
    A BundleV1 as it crosses the wire and rests on disk.

    A bundle that fails verification is rejected and the previous one keeps serving.
    """

    payload: BundleV1
    signature: Annotated[str, Field(title="Signature")]
    signing_key_id: Annotated[str, Field(title="Signing Key Id")]


class EnvelopeSignedBundle(BaseModel):
    data: SignedBundle
