# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SecretStr,
)


class ActivityOut(BaseModel):
    """
    One audited change, identifying what changed, who changed it, and when.
    """

    id: Annotated[int | None, Field(title="Id")]
    table_name: Annotated[str, Field(title="Table Name")]
    record_id: Annotated[str, Field(title="Record Id")]
    action: Annotated[str, Field(title="Action")]
    user_id: Annotated[str, Field(title="User Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]


class AllRequests(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["all_requests"], Field(title="Kind")]


class Name(RootModel[str]):
    root: Annotated[str, Field(max_length=255, min_length=1)]


class AllowedModels(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["models"], Field(title="Kind")]
    names: Annotated[list[Name], Field(max_length=1000, min_length=1, title="Names")]


class AllowedProviders(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["providers"], Field(title="Kind")]
    names: Annotated[list[Name], Field(max_length=1000, min_length=1, title="Names")]


class Budget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["budget"], Field(title="Kind")]
    amount_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Amount Usd")]
    period: Annotated[Literal["day", "month"], Field(title="Period")]
    aggregation: Annotated[Literal["shared", "per_key"], Field(title="Aggregation")]


class BundleManifestEntry(BaseModel):
    """
    The immutable identity of one organization bundle available to a data plane.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    org_id: Annotated[UUID, Field(title="Org Id")]
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]


class ClaimOut(BaseModel):
    claimed: Annotated[bool, Field(title="Claimed")]
    public_signup: Annotated[bool, Field(title="Public Signup")]


class CliAuthApproveIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_code: Annotated[
        str,
        Field(
            description="Device code shown by the CLI",
            max_length=16,
            min_length=8,
            title="User Code",
        ),
    ]
    scope: Annotated[
        Literal["instance", "org"] | None,
        Field(description="Scope the CLI management key should use", title="Scope"),
    ] = "org"
    org_id: Annotated[
        UUID | None,
        Field(
            description="Organization the CLI management key should use for organization scope",
            title="Org Id",
        ),
    ] = None


class CliAuthApprovedOut(BaseModel):
    status: Annotated[Literal["approved"], Field(title="Status")]
    client_name: Annotated[str, Field(title="Client Name")]


class CliAuthPollIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    poll_secret: Annotated[
        str,
        Field(
            description="Polling secret returned when device authorization started",
            max_length=256,
            min_length=1,
            title="Poll Secret",
        ),
    ]


class CliAuthPollOut(BaseModel):
    status: Annotated[Literal["pending", "complete"], Field(title="Status")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    scope: Annotated[Literal["instance", "org"] | None, Field(title="Scope")] = None
    token: Annotated[str | None, Field(title="Token")] = None
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    org_name: Annotated[str | None, Field(title="Org Name")] = None


class CliAuthRequestOut(BaseModel):
    client_name: Annotated[str, Field(title="Client Name")]
    requester: Annotated[str, Field(title="Requester")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    can_approve_instance: Annotated[bool, Field(title="Can Approve Instance")]


class CliAuthStartIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    client_name: Annotated[
        str,
        Field(
            description="Where the CLI runs, e.g. the hostname; becomes the created key's label",
            max_length=80,
            min_length=1,
            title="Client Name",
        ),
    ]


class CliAuthStartOut(BaseModel):
    user_code: Annotated[str, Field(title="User Code")]
    verification_url: Annotated[str, Field(title="Verification Url")]
    poll_secret: Annotated[str, Field(title="Poll Secret")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    expires_in_seconds: Annotated[int, Field(title="Expires In Seconds")]


class CredentialAccess(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["credential_access"], Field(title="Kind")]
    scopes: Annotated[
        list[Literal["platform", "org", "workspace"]],
        Field(max_length=3, min_length=1, title="Scopes"),
    ]


class CursorToken(RootModel[str]):
    root: Annotated[str, Field(max_length=512, min_length=1, pattern="^[A-Za-z0-9_-]+$")]


class DataPlaneInstanceOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    version: Annotated[str, Field(title="Version")]
    bundle_id: Annotated[UUID | None, Field(title="Bundle Id")]
    address: Annotated[str | None, Field(title="Address")]
    status: Annotated[Literal["online", "offline"], Field(title="Status")]
    first_seen: Annotated[AwareDatetime, Field(title="First Seen")]
    last_seen: Annotated[AwareDatetime, Field(title="Last Seen")]


class DeletedOutUUID(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class DeletedOutStr(BaseModel):
    id: Annotated[str, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class MaxOutputTokens(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Effective upstream output-token limit",
            ge=1,
            le=2147483647,
            title="Max Output Tokens",
        ),
    ]


class DeniedUsageEventV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        Literal[1],
        Field(description="Usage event schema version", title="Schema Version"),
    ] = 1
    event_id: Annotated[UUID, Field(description="Idempotency key for event ingestion", title="Event Id")]
    request_id: Annotated[UUID, Field(description="Data-plane request ID", title="Request Id")]
    request_started_at: Annotated[
        AwareDatetime,
        Field(
            description="Timestamp when the logical request began",
            title="Request Started At",
        ),
    ]
    attempt_started_at: Annotated[
        None,
        Field(description="No provider attempt was made", title="Attempt Started At"),
    ] = None
    occurred_at: Annotated[
        AwareDatetime,
        Field(
            description="Timestamp when the attempt or denial completed",
            title="Occurred At",
        ),
    ]
    org_id: Annotated[UUID, Field(description="Organization that made the request", title="Org Id")]
    workspace_id: Annotated[UUID, Field(description="Workspace that made the request", title="Workspace Id")]
    key_id: Annotated[
        str,
        Field(
            description="Caller credential ID used for the request",
            max_length=255,
            min_length=1,
            title="Key Id",
        ),
    ]
    request_source: Annotated[
        Literal["inference_key", "playground"],
        Field(
            description="Whether the request came from an inference key or a Playground session",
            title="Request Source",
        ),
    ]
    user_id: Annotated[
        UUID,
        Field(
            description="Principal that owned the caller credential when the request was made",
            title="User Id",
        ),
    ]
    requested_model_id: Annotated[
        str,
        Field(
            description="Original caller-requested model before routing and fallback",
            max_length=255,
            min_length=1,
            title="Requested Model Id",
        ),
    ]
    requested_capabilities: Annotated[
        list[Literal["tools", "reasoning", "structured_output"]],
        Field(
            description="Original request capabilities before reconciliation",
            title="Requested Capabilities",
        ),
    ]
    model_id: Annotated[
        str,
        Field(
            description="Caller-facing model ID",
            max_length=255,
            min_length=1,
            title="Model Id",
        ),
    ]
    provider_id: Annotated[
        Literal[""],
        Field(description="No provider was selected before denial", title="Provider Id"),
    ] = ""
    bundle_id: Annotated[UUID, Field(description="Policy bundle used for the request", title="Bundle Id")]
    input_tokens: Annotated[
        int,
        Field(description="Total input tokens", ge=0, le=2147483647, title="Input Tokens"),
    ]
    output_tokens: Annotated[
        int,
        Field(
            description="Total output tokens",
            ge=0,
            le=2147483647,
            title="Output Tokens",
        ),
    ]
    cost_usd: Annotated[
        str,
        Field(
            description="Total estimated cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Usd",
        ),
    ]
    cost_input_usd: Annotated[
        str | None,
        Field(
            description="Estimated input cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Input Usd",
        ),
    ] = "0"
    cost_output_usd: Annotated[
        str | None,
        Field(
            description="Estimated output cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Output Usd",
        ),
    ] = "0"
    max_output_tokens: Annotated[
        MaxOutputTokens | None,
        Field(
            description="Effective upstream output-token limit",
            title="Max Output Tokens",
        ),
    ]
    cache_read_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens read from a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Read Tokens",
        ),
    ] = 0
    cache_write_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens written to a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Write Tokens",
        ),
    ] = 0
    latency_ms: Annotated[
        int,
        Field(
            description="Gateway latency in milliseconds: per attempt when routed, end-to-end for a denial before routing",
            ge=0,
            le=2147483647,
            title="Latency Ms",
        ),
    ]
    status: Annotated[
        Literal["denied"],
        Field(description="The request was denied before routing", title="Status"),
    ] = "denied"
    stream: Annotated[bool, Field(description="Whether the response was streamed", title="Stream")]
    credential_id: Annotated[
        None,
        Field(
            description="No provider credential was selected before denial",
            title="Credential Id",
        ),
    ] = None
    credential_scope: Annotated[
        None,
        Field(
            description="No provider credential scope was selected before denial",
            title="Credential Scope",
        ),
    ] = None
    token_usage_source: Annotated[
        Literal["not_applicable"],
        Field(
            description="No upstream token usage for a request denied before routing",
            title="Token Usage Source",
        ),
    ]


class DenyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["deny"], Field(title="Kind")]
    message: Annotated[str, Field(max_length=200, min_length=1, title="Message")]


class EnvelopeClaimOut(BaseModel):
    data: ClaimOut


class EnvelopeCliAuthApprovedOut(BaseModel):
    data: CliAuthApprovedOut


class EnvelopeCliAuthPollOut(BaseModel):
    data: CliAuthPollOut


class EnvelopeCliAuthRequestOut(BaseModel):
    data: CliAuthRequestOut


class EnvelopeCliAuthStartOut(BaseModel):
    data: CliAuthStartOut


class EnvelopeDeletedOutUUID(BaseModel):
    data: DeletedOutUUID


class EnvelopeDeletedOutStr(BaseModel):
    data: DeletedOutStr


class EnvelopeListDataPlaneInstanceOut(BaseModel):
    data: Annotated[list[DataPlaneInstanceOut], Field(title="Data")]


class EventsIngestedOut(BaseModel):
    received: Annotated[int, Field(title="Received")]
    ingested: Annotated[int, Field(title="Ingested")]
    rejected: Annotated[int, Field(title="Rejected")]


class Model(RootModel[str]):
    root: Annotated[str, Field(max_length=255, min_length=1)]


class Fallback(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["fallback"], Field(title="Kind")]
    models: Annotated[list[Model], Field(max_length=4, min_length=1, title="Models")]
    on: Annotated[
        list[Literal["rate_limited", "upstream_unavailable", "timeout"]],
        Field(max_length=3, min_length=1, title="On"),
    ]
    max_attempts: Annotated[int, Field(ge=2, le=5, title="Max Attempts")]
    timeout_ms: Annotated[int, Field(ge=100, le=120000, title="Timeout Ms")]


class HeartbeatOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]


class HeartbeatV1(BaseModel):
    """
    The identity, software version, and single active bundle reported by a data plane.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instance_id: Annotated[
        UUID,
        Field(
            description="Stable ID for this data-plane installation",
            title="Instance Id",
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="Running data-plane software version",
            max_length=100,
            min_length=1,
            title="Version",
        ),
    ]
    bundle_id: Annotated[
        UUID | None,
        Field(
            description="Policy bundle served when exactly one is loaded; otherwise absent",
            title="Bundle Id",
        ),
    ] = None


class InferenceKeyCreatedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    token: Annotated[str, Field(title="Token")]


class InferenceKeyIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[
        str,
        Field(
            description="What this key is for, e.g. staging or the calling app; shown in listings",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]
    user_id: Annotated[
        UUID,
        Field(
            description="Principal whose identity this key carries into policy evaluation",
            title="User Id",
        ),
    ]


class InferenceKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    revoked: Annotated[bool, Field(title="Revoked")]
    label: Annotated[str, Field(title="Label")]
    prefix: Annotated[str, Field(title="Prefix")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class InferenceKeyOwnerOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]


class InferenceKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]


class InstanceRole(RootModel[Literal["owner", "auditor", "data_plane"]]):
    root: Annotated[Literal["owner", "auditor", "data_plane"], Field(title="InstanceRole")]


class InstanceRoleIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    instance_role: Annotated[
        InstanceRole | None,
        Field(description="Instance-wide role to assign, or null to remove instance-wide access"),
    ]


class InvitationAcceptedOut(BaseModel):
    invitation_id: Annotated[UUID, Field(title="Invitation Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    status: Annotated[Literal["accepted"], Field(title="Status")]


class InvitationPreviewOut(BaseModel):
    email: Annotated[str, Field(title="Email")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    org_name: Annotated[str, Field(title="Org Name")]
    org_role: Annotated[str, Field(title="Org Role")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    workspace_name: Annotated[str | None, Field(title="Workspace Name")]
    workspace_role: Annotated[str | None, Field(title="Workspace Role")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]


class InvitationTokenIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: Annotated[
        str,
        Field(
            description="Secret from the shared invitation link",
            max_length=256,
            min_length=1,
            title="Token",
        ),
    ]


class KeyBudgetBucket(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["key"], Field(title="Kind")]
    key_id: Annotated[str, Field(max_length=255, min_length=1, title="Key Id")]


class KeyEntry(BaseModel):
    """
    An active caller credential included in a policy bundle.

    The bundle contains a token hash for authorization and a key ID for usage attribution, never
    the caller's secret token.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    key_id: Annotated[str, Field(max_length=255, min_length=1, title="Key Id")]
    request_source: Annotated[Literal["inference_key", "playground"], Field(title="Request Source")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    token_hash: Annotated[str, Field(title="Token Hash")]
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")] = None


class LoginIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        str,
        Field(
            description="Account email address",
            max_length=320,
            min_length=3,
            title="Email",
        ),
    ]
    password: Annotated[
        str,
        Field(
            description="Account password",
            max_length=1024,
            min_length=1,
            title="Password",
        ),
    ]


class ManagementKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]
    revoked_at: Annotated[AwareDatetime, Field(title="Revoked At")]


class MeOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    instance_role: InstanceRole | None
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class MaxOutputTokens1(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=100000000, title="Max Output Tokens")]


class EgressKind(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_]*$",
            title="Egress Kind",
        ),
    ]


class ModelEntry(BaseModel):
    """
    A routable model: the caller-facing id plus how to reach and bill it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    model_id: Annotated[str, Field(max_length=255, min_length=1, title="Model Id")]
    provider_id: Annotated[
        str,
        Field(
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    upstream_model: Annotated[str, Field(max_length=255, min_length=1, title="Upstream Model")]
    input_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(ge=1, le=100000000, title="Context Window")]
    max_output_tokens: Annotated[MaxOutputTokens1 | None, Field(title="Max Output Tokens")] = None
    input_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(max_length=5, min_length=1, title="Input Modalities"),
    ]
    output_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(max_length=5, min_length=1, title="Output Modalities"),
    ]
    capabilities: Annotated[
        list[Literal["streaming", "tools", "reasoning", "structured_output"]],
        Field(max_length=4, title="Capabilities"),
    ]
    parameter_support: Annotated[
        dict[str, Literal["supported", "unsupported"]] | None,
        Field(max_length=128, title="Parameter Support"),
    ] = None
    egress_kind: Annotated[EgressKind | None, Field(title="Egress Kind")] = None


class EgressKind1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Per-model egress adapter override",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_]*$",
            title="Egress Kind",
        ),
    ]


class MaxOutputTokens2(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Max completion tokens; requests are clamped to it",
            ge=1,
            le=100000000,
            title="Max Output Tokens",
        ),
    ]


class ModelIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model_id: Annotated[
        str,
        Field(
            description="Caller-facing model name",
            max_length=255,
            min_length=1,
            title="Model Id",
        ),
    ]
    provider_id: Annotated[
        str,
        Field(
            description="Provider id the model routes to",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    upstream_model: Annotated[
        str | None,
        Field(
            description="Model name sent to the provider, lets model_id be an alias; defaults to model_id",
            max_length=255,
            title="Upstream Model",
        ),
    ] = ""
    egress_kind: Annotated[
        EgressKind1 | None,
        Field(description="Per-model egress adapter override", title="Egress Kind"),
    ] = None
    input_price_per_mtok: Annotated[
        str | None,
        Field(
            description="USD per million input tokens",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Input Price Per Mtok",
        ),
    ] = "0"
    output_price_per_mtok: Annotated[
        str | None,
        Field(
            description="USD per million output tokens",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Output Price Per Mtok",
        ),
    ] = "0"
    cache_read_price_per_mtok: Annotated[
        str | None,
        Field(
            description="USD per million cache-read input tokens",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cache Read Price Per Mtok",
        ),
    ] = "0"
    cache_write_price_per_mtok: Annotated[
        str | None,
        Field(
            description="USD per million cache-write input tokens",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cache Write Price Per Mtok",
        ),
    ] = "0"
    context_window: Annotated[
        int | None,
        Field(
            description="Context window in tokens",
            ge=1,
            le=100000000,
            title="Context Window",
        ),
    ] = 128000
    max_output_tokens: Annotated[
        MaxOutputTokens2 | None,
        Field(
            description="Max completion tokens; requests are clamped to it",
            title="Max Output Tokens",
        ),
    ] = None
    input_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(
            description="Accepted input modalities",
            max_length=16,
            min_length=1,
            title="Input Modalities",
        ),
    ]
    output_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(
            description="Produced output modalities",
            max_length=16,
            min_length=1,
            title="Output Modalities",
        ),
    ]
    capabilities: Annotated[
        list[Literal["streaming", "tools", "reasoning", "structured_output"]] | None,
        Field(
            description="Capabilities supported by the model",
            max_length=4,
            title="Capabilities",
        ),
    ] = None
    parameter_support: Annotated[
        dict[str, Literal["supported", "unsupported"]] | None,
        Field(
            description="Known support for canonical request parameters; an absent parameter is unknown",
            max_length=128,
            title="Parameter Support",
        ),
    ] = None


class ModelOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    upstream_model: Annotated[str, Field(title="Upstream Model")]
    egress_kind: Annotated[str | None, Field(title="Egress Kind")]
    input_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(title="Context Window")]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")]
    input_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(title="Input Modalities"),
    ]
    output_modalities: Annotated[
        list[Literal["text", "image", "audio", "video", "pdf"]],
        Field(title="Output Modalities"),
    ]
    capabilities: Annotated[
        list[Literal["streaming", "tools", "reasoning", "structured_output"]],
        Field(title="Capabilities"),
    ]
    parameter_support: Annotated[dict[str, Literal["supported", "unsupported"]], Field(title="Parameter Support")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class OrgCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Org name, e.g. My Org",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    slug: Annotated[
        str | None,
        Field(
            description="Organization handle, globally unique and usable in place of the id; derived from the name when omitted",
            max_length=63,
            pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$",
            title="Slug",
        ),
    ] = ""


class WorkspaceRole(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Role to grant in the selected workspace",
            pattern="^(admin|member|viewer)$",
            title="Workspace Role",
        ),
    ]


class OrgInvitationCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        str,
        Field(
            description="Email address that must match the account accepting the invitation",
            max_length=320,
            min_length=3,
            title="Email",
        ),
    ]
    org_role: Annotated[
        str,
        Field(
            description="Organization role to grant",
            pattern="^(admin|member)$",
            title="Org Role",
        ),
    ]
    workspace_id: Annotated[
        UUID | None,
        Field(description="Optional workspace to join", title="Workspace Id"),
    ] = None
    workspace_role: Annotated[
        WorkspaceRole | None,
        Field(
            description="Role to grant in the selected workspace",
            title="Workspace Role",
        ),
    ] = None


class OrgInvitationOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    email: Annotated[str, Field(title="Email")]
    org_role: Annotated[str, Field(title="Org Role")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    workspace_role: Annotated[str | None, Field(title="Workspace Role")]
    created_by_user_id: Annotated[UUID | None, Field(title="Created By User Id")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    accepted_at: Annotated[AwareDatetime | None, Field(title="Accepted At")]
    accepted_by_user_id: Annotated[UUID | None, Field(title="Accepted By User Id")]
    revoked_at: Annotated[AwareDatetime | None, Field(title="Revoked At")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    status: Annotated[Literal["pending", "expired", "accepted", "revoked"], Field(title="Status")]


class OrgInvitationRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]
    revoked_at: Annotated[AwareDatetime, Field(title="Revoked At")]


class OrgOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    slug: Annotated[str, Field(title="Slug")]
    personal_for: Annotated[UUID | None, Field(title="Personal For")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class OrgRole(RootModel[Literal["owner", "admin", "member", "data_plane"]]):
    root: Annotated[Literal["owner", "admin", "member", "data_plane"], Field(title="OrgRole")]


class OrgSummaryOut(BaseModel):
    total: Annotated[
        int,
        Field(
            description="Number of organizations currently on the instance, including personal organizations",
            ge=0,
            title="Total",
        ),
    ]


class Name2(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Replacement organization name",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class OrgUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[Name2 | None, Field(description="Replacement organization name", title="Name")] = None


class PageInfo(BaseModel):
    next_cursor: Annotated[str | None, Field(title="Next Cursor")]


class PasswordChangeIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    current_password: Annotated[
        str,
        Field(
            description="Current account password",
            max_length=1024,
            min_length=1,
            title="Current Password",
        ),
    ]
    new_password: Annotated[
        str,
        Field(
            description="Replacement password; at least 8 characters",
            max_length=1024,
            min_length=8,
            title="New Password",
        ),
    ]


class PasswordChangedOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    status: Annotated[Literal["changed"], Field(title="Status")]


class Permission(
    RootModel[
        Literal[
            "organizations.read",
            "organizations.create",
            "organizations.update",
            "organizations.delete",
            "principals.read",
            "principals.manage",
            "members.read",
            "members.manage",
            "workspaces.read",
            "workspaces.create",
            "workspaces.update",
            "workspaces.delete",
            "catalog.read",
            "catalog.manage",
            "provider-credentials.read",
            "provider-credentials.manage",
            "inference-keys.read",
            "inference-keys.manage",
            "policies.read",
            "policies.manage",
            "playground.execute",
            "policy-state.sync",
            "bundles.read",
            "usage.read",
            "usage.ingest",
            "data-planes.read",
            "data-planes.heartbeat",
            "audit.read",
            "management-keys.read",
            "management-keys.issue",
            "management-keys.revoke",
        ]
    ]
):
    root: Annotated[
        Literal[
            "organizations.read",
            "organizations.create",
            "organizations.update",
            "organizations.delete",
            "principals.read",
            "principals.manage",
            "members.read",
            "members.manage",
            "workspaces.read",
            "workspaces.create",
            "workspaces.update",
            "workspaces.delete",
            "catalog.read",
            "catalog.manage",
            "provider-credentials.read",
            "provider-credentials.manage",
            "inference-keys.read",
            "inference-keys.manage",
            "policies.read",
            "policies.manage",
            "playground.execute",
            "policy-state.sync",
            "bundles.read",
            "usage.read",
            "usage.ingest",
            "data-planes.read",
            "data-planes.heartbeat",
            "audit.read",
            "management-keys.read",
            "management-keys.issue",
            "management-keys.revoke",
        ],
        Field(title="Permission"),
    ]


class PlaygroundSessionEndedOut(BaseModel):
    status: Annotated[Literal["ended"], Field(title="Status")]


class PlaygroundSessionReadyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    status: Annotated[Literal["ready"], Field(title="Status")]


class PolicyOrder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy_ids: Annotated[
        list[UUID],
        Field(
            description="Every workspace policy ID, from first to last evaluation priority",
            title="Policy Ids",
        ),
    ]


class PolicyStateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    org_ids: Annotated[
        list[UUID],
        Field(
            description="Organizations whose current budget state is requested",
            max_length=1000,
            min_length=1,
            title="Org Ids",
        ),
    ]


class Name3(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Replacement display name; omit to leave unchanged",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class Priority(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Replacement priority, with lower numbers first; omit to leave unchanged",
            ge=0,
            le=10000,
            title="Priority",
        ),
    ]


class PriceLimit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["price_limit"], Field(title="Kind")]
    max_input_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Max Input Price Per Mtok")]
    max_output_price_per_mtok: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Max Output Price Per Mtok")]


class ProviderCredentialIn(BaseModel):
    """
    A provider API key and the metadata used to select it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Annotated[
        str,
        Field(
            description="Provider name from the catalog, e.g. openai",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider",
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Handle for this key within the provider and scope, e.g. prod or backup",
            max_length=80,
            min_length=1,
            pattern="^[A-Za-z0-9][A-Za-z0-9_.-]*$",
            title="Name",
        ),
    ] = "default"
    value: Annotated[
        SecretStr,
        Field(
            description="The provider API key; stored securely and never returned",
            max_length=16384,
            min_length=1,
            title="Value",
        ),
    ]
    priority: Annotated[
        int | None,
        Field(
            description="Lower is tried first; ties break by name",
            ge=0,
            le=1000000,
            title="Priority",
        ),
    ] = 100


class ProviderCredentialOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    provider_name: Annotated[str, Field(title="Provider Name")]
    name: Annotated[str, Field(title="Name")]
    priority: Annotated[int, Field(title="Priority")]
    enabled: Annotated[bool, Field(title="Enabled")]
    version: Annotated[int, Field(title="Version")]
    status: Annotated[Literal["unknown", "live", "invalid", "rate_limited"], Field(title="Status")]
    status_at: Annotated[AwareDatetime | None, Field(title="Status At")]
    fingerprint: Annotated[str, Field(title="Fingerprint")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    scope: Annotated[Literal["platform", "org", "workspace"], Field(title="Scope")]


class Priority1(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Replacement selection priority; lower values are tried first",
            ge=0,
            le=1000000,
            title="Priority",
        ),
    ]


class ProviderCredentialUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    priority: Annotated[
        Priority1 | None,
        Field(
            description="Replacement selection priority; lower values are tried first",
            title="Priority",
        ),
    ] = None
    enabled: Annotated[
        bool | None,
        Field(
            description="Whether the credential may be selected for requests",
            title="Enabled",
        ),
    ] = None


class ProviderCredentialValueIn(BaseModel):
    """
    A rotation: the same credential, a new value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    value: Annotated[
        SecretStr,
        Field(
            description="The replacement provider API key",
            max_length=16384,
            min_length=1,
            title="Value",
        ),
    ]


class AcceptedParams(RootModel[list[str]]):
    root: Annotated[list[str], Field(max_length=256, title="Accepted Params")]


class ProviderEntry(BaseModel):
    """
    An upstream LLM provider endpoint and its supported request parameters.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider_id: Annotated[
        str,
        Field(
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    kind: Annotated[
        str,
        Field(max_length=63, min_length=1, pattern="^[a-z0-9][a-z0-9_]*$", title="Kind"),
    ]
    base_url: Annotated[AnyUrl, Field(title="Base Url")]
    param_aliases: Annotated[dict[str, str] | None, Field(max_length=256, title="Param Aliases")] = None
    accepted_params: Annotated[AcceptedParams | None, Field(title="Accepted Params")] = None
    params_closed: Annotated[bool | None, Field(title="Params Closed")] = False


class AcceptedParams1(RootModel[list[str]]):
    root: Annotated[
        list[str],
        Field(
            description="Params known accepted beyond the core; consulted when params_closed",
            max_length=256,
            title="Accepted Params",
        ),
    ]


class ProviderIn(BaseModel):
    """
    An upstream provider endpoint and its request-profile settings.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider_id: Annotated[
        str,
        Field(
            description="Provider name, e.g. openai",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    kind: Annotated[
        str | None,
        Field(
            description="Adapter kind",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_]*$",
            title="Kind",
        ),
    ] = "openai_compatible"
    base_url: Annotated[
        AnyUrl,
        Field(
            description="OpenAI-compatible endpoint, e.g. https://api.groq.com/openai/v1",
            title="Base Url",
        ),
    ]
    icon: Annotated[
        str | None,
        Field(
            description="Provider mark as a standalone 24x24 SVG document, or an empty string when no icon is available. Clients must sanitize this untrusted markup before rendering it",
            max_length=65536,
            title="Icon",
        ),
    ] = ""
    param_aliases: Annotated[
        dict[str, str] | None,
        Field(
            description="Canonical param name to this provider's spelling",
            max_length=256,
            title="Param Aliases",
        ),
    ] = None
    accepted_params: Annotated[
        AcceptedParams1 | None,
        Field(
            description="Params known accepted beyond the core; consulted when params_closed",
            title="Accepted Params",
        ),
    ] = None
    params_closed: Annotated[
        bool | None,
        Field(
            description="True when the provider's request schema rejects unknown params",
            title="Params Closed",
        ),
    ] = False


class ProviderOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    kind: Annotated[str, Field(title="Kind")]
    base_url: Annotated[str, Field(title="Base Url")]
    icon: Annotated[str, Field(title="Icon")]
    param_aliases: Annotated[dict[str, str], Field(title="Param Aliases")]
    accepted_params: Annotated[list[str] | None, Field(title="Accepted Params")]
    params_closed: Annotated[bool, Field(title="Params Closed")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class RequestLimits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["request_limits"], Field(title="Kind")]
    max_output_tokens: Annotated[int, Field(ge=1, title="Max Output Tokens")]


class RequestMatchInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["request"], Field(title="Kind")]
    models: Annotated[
        list[Model] | None,
        Field(max_length=1000, title="Models", validate_default=True),
    ] = []
    stream: Annotated[bool | None, Field(title="Stream")] = None
    capabilities: Annotated[
        list[Literal["tools", "reasoning", "structured_output"]] | None,
        Field(max_length=3, title="Capabilities"),
    ] = []


class RequestMatchOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["request"], Field(title="Kind")]
    models: Annotated[list[Model], Field(max_length=1000, title="Models")]
    stream: Annotated[bool | None, Field(title="Stream")]
    capabilities: Annotated[
        list[Literal["tools", "reasoning", "structured_output"]],
        Field(max_length=3, title="Capabilities"),
    ]


class MaxOutputTokens3(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Effective upstream output-token limit",
            ge=1,
            le=2147483647,
            title="Max Output Tokens",
        ),
    ]


class RoutedUsageEventV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        Literal[1],
        Field(description="Usage event schema version", title="Schema Version"),
    ] = 1
    event_id: Annotated[UUID, Field(description="Idempotency key for event ingestion", title="Event Id")]
    request_id: Annotated[UUID, Field(description="Data-plane request ID", title="Request Id")]
    request_started_at: Annotated[
        AwareDatetime,
        Field(
            description="Timestamp when the logical request began",
            title="Request Started At",
        ),
    ]
    attempt_started_at: Annotated[
        AwareDatetime,
        Field(
            description="Timestamp when the provider attempt began",
            title="Attempt Started At",
        ),
    ]
    occurred_at: Annotated[
        AwareDatetime,
        Field(
            description="Timestamp when the attempt or denial completed",
            title="Occurred At",
        ),
    ]
    org_id: Annotated[UUID, Field(description="Organization that made the request", title="Org Id")]
    workspace_id: Annotated[UUID, Field(description="Workspace that made the request", title="Workspace Id")]
    key_id: Annotated[
        str,
        Field(
            description="Caller credential ID used for the request",
            max_length=255,
            min_length=1,
            title="Key Id",
        ),
    ]
    request_source: Annotated[
        Literal["inference_key", "playground"],
        Field(
            description="Whether the request came from an inference key or a Playground session",
            title="Request Source",
        ),
    ]
    user_id: Annotated[
        UUID,
        Field(
            description="Principal that owned the caller credential when the request was made",
            title="User Id",
        ),
    ]
    requested_model_id: Annotated[
        str,
        Field(
            description="Original caller-requested model before routing and fallback",
            max_length=255,
            min_length=1,
            title="Requested Model Id",
        ),
    ]
    requested_capabilities: Annotated[
        list[Literal["tools", "reasoning", "structured_output"]],
        Field(
            description="Original request capabilities before reconciliation",
            title="Requested Capabilities",
        ),
    ]
    model_id: Annotated[
        str,
        Field(
            description="Caller-facing model ID",
            max_length=255,
            min_length=1,
            title="Model Id",
        ),
    ]
    provider_id: Annotated[
        str,
        Field(
            description="Provider that served the request",
            max_length=63,
            min_length=1,
            title="Provider Id",
        ),
    ]
    bundle_id: Annotated[UUID, Field(description="Policy bundle used for the request", title="Bundle Id")]
    input_tokens: Annotated[
        int,
        Field(description="Total input tokens", ge=0, le=2147483647, title="Input Tokens"),
    ]
    output_tokens: Annotated[
        int,
        Field(
            description="Total output tokens",
            ge=0,
            le=2147483647,
            title="Output Tokens",
        ),
    ]
    cost_usd: Annotated[
        str,
        Field(
            description="Total estimated cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Usd",
        ),
    ]
    cost_input_usd: Annotated[
        str | None,
        Field(
            description="Estimated input cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Input Usd",
        ),
    ] = "0"
    cost_output_usd: Annotated[
        str | None,
        Field(
            description="Estimated output cost in USD",
            pattern="^\\d+(?:\\.\\d+)?$",
            title="Cost Output Usd",
        ),
    ] = "0"
    max_output_tokens: Annotated[
        MaxOutputTokens3 | None,
        Field(
            description="Effective upstream output-token limit",
            title="Max Output Tokens",
        ),
    ]
    cache_read_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens read from a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Read Tokens",
        ),
    ] = 0
    cache_write_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens written to a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Write Tokens",
        ),
    ] = 0
    latency_ms: Annotated[
        int,
        Field(
            description="Gateway latency in milliseconds: per attempt when routed, end-to-end for a denial before routing",
            ge=0,
            le=2147483647,
            title="Latency Ms",
        ),
    ]
    status: Annotated[
        Literal[
            "ok",
            "upstream_error",
            "timeout",
            "cancelled",
            "credential_rejected",
            "rate_limited",
        ],
        Field(description="How the routed request ended", title="Status"),
    ]
    stream: Annotated[bool, Field(description="Whether the response was streamed", title="Stream")]
    credential_id: Annotated[
        UUID,
        Field(
            description="Provider credential used for the request",
            title="Credential Id",
        ),
    ]
    credential_scope: Annotated[
        Literal["platform", "org", "workspace"],
        Field(
            description="Scope of the provider credential used for the request",
            title="Credential Scope",
        ),
    ]
    token_usage_source: Annotated[
        Literal["provider", "estimated"],
        Field(
            description="provider: counts accepted from upstream; estimated: gateway estimation was needed, possibly retaining partial provider counts. Independent of catalog-priced cost estimates",
            title="Token Usage Source",
        ),
    ]


class ScopeLevel(RootModel[Literal["instance", "org", "workspace"]]):
    root: Annotated[Literal["instance", "org", "workspace"], Field(title="ScopeLevel")]


class SecretPurpose(RootModel[Literal["provider"]]):
    root: Annotated[
        Literal["provider"],
        Field(
            description="The kind of credential addressed by a secret reference.",
            title="SecretPurpose",
        ),
    ]


class SecretRef(BaseModel):
    """
    A stable reference to a secret value and the scope that owns it.
    """

    purpose: SecretPurpose
    service: Annotated[str, Field(title="Service")]
    name: Annotated[str, Field(title="Name")]
    secret_id: Annotated[UUID, Field(title="Secret Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")] = None


class KeyId(RootModel[str]):
    root: Annotated[str, Field(max_length=255, min_length=1)]


class SelectedKeys(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["selected_keys"], Field(title="Kind")]
    key_ids: Annotated[list[KeyId], Field(max_length=1000, min_length=1, title="Key Ids")]


class SelectedUsers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["selected_users"], Field(title="Kind")]
    user_ids: Annotated[list[UUID], Field(max_length=1000, min_length=1, title="User Ids")]


class ServiceAccountIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the service account",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    instance_role: Annotated[
        InstanceRole | None,
        Field(description="Optional instance-wide role for the service account"),
    ] = None


class SharedBudgetBucket(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["shared"], Field(title="Kind")]


class InvitationToken(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Invitation authorizing this account signup",
            max_length=256,
            min_length=1,
            title="Invitation Token",
        ),
    ]


class SignupIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        str,
        Field(
            description="Email address for the new account",
            max_length=320,
            min_length=3,
            title="Email",
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Display name; defaults to the email address",
            max_length=200,
            title="Name",
        ),
    ] = ""
    password: Annotated[
        str,
        Field(
            description="Password for the new account; at least 8 characters",
            max_length=1024,
            min_length=8,
            title="Password",
        ),
    ]
    invitation_token: Annotated[
        InvitationToken | None,
        Field(
            description="Invitation authorizing this account signup",
            title="Invitation Token",
        ),
    ] = None


class StrictParameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["strict_parameters"], Field(title="Kind")]


class TaxonomyChangeCounts(BaseModel):
    created: Annotated[int, Field(title="Created")]
    updated: Annotated[int, Field(title="Updated")]
    unchanged: Annotated[int, Field(title="Unchanged")]


class TaxonomyOut(BaseModel):
    providers: Annotated[list[ProviderOut], Field(title="Providers")]
    models: Annotated[list[ModelOut], Field(title="Models")]


class TaxonomySpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    providers: Annotated[
        list[ProviderIn] | None,
        Field(
            description="Provider endpoints to create or update",
            max_length=1000,
            title="Providers",
        ),
    ] = None
    models: Annotated[
        list[ModelIn] | None,
        Field(
            description="Routable models to create or update",
            max_length=10000,
            title="Models",
        ),
    ] = None


class TokenUsageSource(RootModel[Literal["provider", "estimated", "not_applicable"]]):
    root: Annotated[
        Literal["provider", "estimated", "not_applicable"],
        Field(title="TokenUsageSource"),
    ]


class UsageEventOut(BaseModel):
    event_id: Annotated[UUID, Field(title="Event Id")]
    request_id: Annotated[UUID, Field(title="Request Id")]
    request_started_at: Annotated[AwareDatetime, Field(title="Request Started At")]
    attempt_started_at: Annotated[AwareDatetime | None, Field(title="Attempt Started At")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    key_id: Annotated[str, Field(title="Key Id")]
    request_source: Annotated[Literal["inference_key", "playground"], Field(title="Request Source")]
    user_id: Annotated[UUID, Field(title="User Id")]
    requested_model_id: Annotated[str, Field(title="Requested Model Id")]
    requested_capabilities: Annotated[
        list[Literal["tools", "reasoning", "structured_output"]],
        Field(title="Requested Capabilities"),
    ]
    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]
    token_usage_source: Annotated[
        TokenUsageSource,
        Field(
            description="Token-count provenance: provider, estimated (including partial provider counts), or not_applicable for denials; independent of cost estimates"
        ),
    ]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")]
    cost_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cost Usd")]
    cost_input_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cost Input Usd")]
    cost_output_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Cost Output Usd")]
    cache_read_tokens: Annotated[int, Field(title="Cache Read Tokens")]
    cache_write_tokens: Annotated[int, Field(title="Cache Write Tokens")]
    latency_ms: Annotated[int, Field(title="Latency Ms")]
    status: Annotated[
        Literal[
            "ok",
            "upstream_error",
            "denied",
            "timeout",
            "cancelled",
            "credential_rejected",
            "rate_limited",
        ],
        Field(title="Status"),
    ]
    stream: Annotated[bool, Field(title="Stream")]
    credential_id: Annotated[UUID | None, Field(title="Credential Id")]
    credential_scope: Annotated[Literal["platform", "org", "workspace"] | None, Field(title="Credential Scope")]


class UserOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    instance_role: Annotated[str | None, Field(title="Instance Role")]
    service_account: Annotated[bool, Field(title="Service Account")]
    managing_org_id: Annotated[UUID | None, Field(title="Managing Org Id")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Any | None, Field(title="Input")] = None
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None


class WorkspaceCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Workspace name, e.g. Staging",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    slug: Annotated[
        str | None,
        Field(
            description="Workspace handle, unique in the org and usable in place of the id; derived from the name when omitted",
            max_length=63,
            pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$",
            title="Slug",
        ),
    ] = ""


class WorkspaceMemberCandidateOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]


class WorkspaceOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    name: Annotated[str, Field(title="Name")]
    slug: Annotated[str, Field(title="Slug")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class WorkspaceRoleModel(RootModel[Literal["admin", "member", "viewer"]]):
    root: Annotated[Literal["admin", "member", "viewer"], Field(title="WorkspaceRole")]


class WorkspaceTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[Literal["workspace"], Field(title="Kind")]


class Name4(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Replacement workspace name",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class WorkspaceUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[Name4 | None, Field(description="Replacement workspace name", title="Name")] = None


class BudgetBucketStatus(BaseModel):
    bucket: Annotated[
        SharedBudgetBucket | KeyBudgetBucket,
        Field(discriminator="kind", title="Bucket"),
    ]
    spent_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Spent Usd")]
    remaining_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Remaining Usd")]
    exhausted: Annotated[bool, Field(title="Exhausted")]


class BudgetRuleStatus(BaseModel):
    rule_index: Annotated[int, Field(ge=0, lt=100, title="Rule Index")]
    aggregation: Annotated[Literal["shared", "per_key"], Field(title="Aggregation")]
    amount_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Amount Usd")]
    period: Annotated[Literal["day", "month"], Field(title="Period")]
    window_start: Annotated[AwareDatetime, Field(title="Window Start")]
    window_end: Annotated[AwareDatetime, Field(title="Window End")]
    buckets: Annotated[list[BudgetBucketStatus], Field(title="Buckets")]
    next_bucket: Annotated[SharedBudgetBucket | KeyBudgetBucket | None, Field(title="Next Bucket")]


class ExhaustedBuckets(RootModel[SharedBudgetBucket | KeyBudgetBucket]):
    root: Annotated[SharedBudgetBucket | KeyBudgetBucket, Field(discriminator="kind")]


class BudgetState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy_id: Annotated[UUID, Field(title="Policy Id")]
    rule_index: Annotated[int, Field(ge=0, lt=100, title="Rule Index")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    target: Annotated[
        WorkspaceTarget | SelectedUsers | SelectedKeys,
        Field(discriminator="kind", title="Target"),
    ]
    match: Annotated[AllRequests | RequestMatchOutput, Field(discriminator="kind", title="Match")]
    aggregation: Annotated[Literal["shared", "per_key"], Field(title="Aggregation")]
    amount_usd: Annotated[str, Field(pattern="^\\d+(?:\\.\\d+)?$", title="Amount Usd")]
    period: Annotated[Literal["day", "month"], Field(title="Period")]
    window_start: Annotated[AwareDatetime, Field(title="Window Start")]
    window_end: Annotated[AwareDatetime, Field(title="Window End")]
    exhausted_buckets: Annotated[list[ExhaustedBuckets], Field(title="Exhausted Buckets")]


class BundleManifest(BaseModel):
    """
    The complete set of organization bundles one data plane may serve.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bundles: Annotated[list[BundleManifestEntry], Field(title="Bundles")]


class CredentialEntry(BaseModel):
    """
    A provider credential reference, priority, and version included in a policy bundle.

    The secret value is not included. A version change tells data planes to refresh their cached value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ref: SecretRef
    priority: Annotated[int, Field(title="Priority")]
    version: Annotated[int, Field(title="Version")]


class EnrollOut(BaseModel):
    orgs: Annotated[list[OrgOut], Field(title="Orgs")]
    personal_org_id: Annotated[UUID | None, Field(title="Personal Org Id")]
    pending_invitations: Annotated[list[InvitationPreviewOut], Field(title="Pending Invitations")]


class EnvelopeBundleManifest(BaseModel):
    data: BundleManifest


class EnvelopeEnrollOut(BaseModel):
    data: EnrollOut


class EnvelopeEventsIngestedOut(BaseModel):
    data: EventsIngestedOut


class EnvelopeHeartbeatOut(BaseModel):
    data: HeartbeatOut


class EnvelopeInferenceKeyCreatedOut(BaseModel):
    data: InferenceKeyCreatedOut


class EnvelopeInferenceKeyRevokedOut(BaseModel):
    data: InferenceKeyRevokedOut


class EnvelopeInvitationAcceptedOut(BaseModel):
    data: InvitationAcceptedOut


class EnvelopeInvitationPreviewOut(BaseModel):
    data: InvitationPreviewOut


class EnvelopeManagementKeyRevokedOut(BaseModel):
    data: ManagementKeyRevokedOut


class EnvelopeMeOut(BaseModel):
    data: MeOut


class EnvelopeModelOut(BaseModel):
    data: ModelOut


class EnvelopeOrgInvitationRevokedOut(BaseModel):
    data: OrgInvitationRevokedOut


class EnvelopeOrgOut(BaseModel):
    data: OrgOut


class EnvelopeOrgSummaryOut(BaseModel):
    data: OrgSummaryOut


class EnvelopePasswordChangedOut(BaseModel):
    data: PasswordChangedOut


class EnvelopePlaygroundSessionEndedOut(BaseModel):
    data: PlaygroundSessionEndedOut


class EnvelopePlaygroundSessionReadyOut(BaseModel):
    data: PlaygroundSessionReadyOut


class EnvelopeProviderCredentialOut(BaseModel):
    data: ProviderCredentialOut


class EnvelopeProviderOut(BaseModel):
    data: ProviderOut


class EnvelopeTaxonomyOut(BaseModel):
    data: TaxonomyOut


class EnvelopeUserOut(BaseModel):
    data: UserOut


class EnvelopeWorkspaceOut(BaseModel):
    data: WorkspaceOut


class EnvelopeListInferenceKeyOut(BaseModel):
    data: Annotated[list[InferenceKeyOut], Field(title="Data")]


class EnvelopeListInferenceKeyOwnerOut(BaseModel):
    data: Annotated[list[InferenceKeyOwnerOut], Field(title="Data")]


class EnvelopeListOrgInvitationOut(BaseModel):
    data: Annotated[list[OrgInvitationOut], Field(title="Data")]


class EnvelopeListProviderCredentialOut(BaseModel):
    data: Annotated[list[ProviderCredentialOut], Field(title="Data")]


class EnvelopeListUserOut(BaseModel):
    data: Annotated[list[UserOut], Field(title="Data")]


class EnvelopeListWorkspaceMemberCandidateOut(BaseModel):
    data: Annotated[list[WorkspaceMemberCandidateOut], Field(title="Data")]


class EnvelopeListWorkspaceOut(BaseModel):
    data: Annotated[list[WorkspaceOut], Field(title="Data")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class ManagementKeyIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: Annotated[
        list[Permission],
        Field(
            description="Explicit maximum permissions carried by the key",
            min_length=1,
            title="Permissions",
        ),
    ]
    label: Annotated[
        str,
        Field(
            description="Where this key lives, such as ci, laptop, or data-plane",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Optional expiration timestamp with a timezone",
            title="Expires At",
        ),
    ] = None


class ManagementKeyPermissionsIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: Annotated[
        list[Permission],
        Field(
            description="Explicit maximum permissions carried by the key",
            min_length=1,
            title="Permissions",
        ),
    ]


class MembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    role: OrgRole
    status: Annotated[Literal["member"], Field(title="Status")]


class MyPermissionsOut(BaseModel):
    permissions: Annotated[
        list[Permission],
        Field(
            description="Permissions the credential can exercise at the requested scope",
            title="Permissions",
        ),
    ]


class OrgInvitationMintedOut(BaseModel):
    invitation: OrgInvitationOut
    url: Annotated[str, Field(title="Url")]


class OrgMemberOut(BaseModel):
    """
    A human user or service account that belongs to an organization.
    """

    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]
    role: OrgRole
    status: Annotated[Literal["member"], Field(title="Status")]
    managed: Annotated[bool | None, Field(title="Managed")] = False


class OrgMembershipIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[OrgRole, Field(description="Organization role to grant")]


class OrgPolicyState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    org_id: Annotated[UUID, Field(title="Org Id")]
    budgets: Annotated[list[BudgetState], Field(title="Budgets")]


class OrgServiceAccountIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the service account",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    management_key: Annotated[
        ManagementKeyIn,
        Field(description="Initial organization-scoped management key to create for the service account"),
    ]


class PageEnvelopeActivityOut(BaseModel):
    data: Annotated[list[ActivityOut], Field(max_length=200, title="Data")]
    page: PageInfo


class PageEnvelopeOrgOut(BaseModel):
    data: Annotated[list[OrgOut], Field(max_length=200, title="Data")]
    page: PageInfo


class PageEnvelopeUsageEventOut(BaseModel):
    data: Annotated[list[UsageEventOut], Field(max_length=200, title="Data")]
    page: PageInfo


class PolicyState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    computed_at: Annotated[AwareDatetime, Field(title="Computed At")]
    organizations: Annotated[list[OrgPolicyState], Field(title="Organizations")]


class RuleDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    match: Annotated[AllRequests | RequestMatchInput, Field(discriminator="kind", title="Match")]
    action: Annotated[
        AllowedModels | AllowedProviders | DenyRequest | StrictParameters | PriceLimit | RequestLimits | CredentialAccess | Fallback | Budget,
        Field(discriminator="kind", title="Action"),
    ]


class RuleDefinitionOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    match: Annotated[AllRequests | RequestMatchOutput, Field(discriminator="kind", title="Match")]
    action: Annotated[
        AllowedModels | AllowedProviders | DenyRequest | StrictParameters | PriceLimit | RequestLimits | CredentialAccess | Fallback | Budget,
        Field(discriminator="kind", title="Action"),
    ]


class Scope(BaseModel):
    level: ScopeLevel
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")] = None


class TaxonomyApplyOut(BaseModel):
    dry_run: Annotated[bool, Field(title="Dry Run")]
    providers: TaxonomyChangeCounts
    models: TaxonomyChangeCounts


class WorkspaceMembershipIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[WorkspaceRoleModel, Field(description="Workspace role to grant")]


class WorkspaceMembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]
    role: WorkspaceRoleModel
    status: Annotated[Literal["member"], Field(title="Status")]


class Catalog(BaseModel):
    """
    Everything routable in one org: providers, the models that point at them, and the credentials
    they are reached with.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    providers: Annotated[list[ProviderEntry], Field(title="Providers")]
    models: Annotated[list[ModelEntry], Field(title="Models")]
    credentials: Annotated[list[CredentialEntry] | None, Field(title="Credentials", validate_default=True)] = []


class EnvelopeMembershipOut(BaseModel):
    data: MembershipOut


class EnvelopeMyPermissionsOut(BaseModel):
    data: MyPermissionsOut


class EnvelopeOrgInvitationMintedOut(BaseModel):
    data: OrgInvitationMintedOut


class EnvelopePolicyState(BaseModel):
    data: PolicyState


class EnvelopeTaxonomyApplyOut(BaseModel):
    data: TaxonomyApplyOut


class EnvelopeWorkspaceMembershipOut(BaseModel):
    data: WorkspaceMembershipOut


class EnvelopeListOrgMemberOut(BaseModel):
    data: Annotated[list[OrgMemberOut], Field(title="Data")]


class EnvelopeListWorkspaceMembershipOut(BaseModel):
    data: Annotated[list[WorkspaceMembershipOut], Field(title="Data")]


class ManagementKeyCreatedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    prefix: Annotated[str, Field(title="Prefix")]
    permissions: Annotated[list[Permission], Field(title="Permissions")]
    label: Annotated[str, Field(title="Label")]
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")]
    revoked_at: Annotated[AwareDatetime | None, Field(title="Revoked At")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    scope: Scope
    status: Annotated[Literal["active", "expired", "revoked"], Field(title="Status")]
    token: Annotated[str, Field(title="Token")]


class ManagementKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    prefix: Annotated[str, Field(title="Prefix")]
    permissions: Annotated[list[Permission], Field(title="Permissions")]
    label: Annotated[str, Field(title="Label")]
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")]
    revoked_at: Annotated[AwareDatetime | None, Field(title="Revoked At")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    scope: Scope
    status: Annotated[Literal["active", "expired", "revoked"], Field(title="Status")]


class OrgServiceAccountCreatedOut(BaseModel):
    service_account: UserOut
    membership: MembershipOut
    management_key: ManagementKeyCreatedOut


class PolicyDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target: Annotated[
        WorkspaceTarget | SelectedUsers | SelectedKeys,
        Field(discriminator="kind", title="Target"),
    ]
    rules: Annotated[
        list[RuleDefinitionInput],
        Field(
            description="Unordered inline rule definitions; a policy may contain at most one fallback rule",
            max_length=100,
            min_length=1,
            title="Rules",
        ),
    ]


class PolicyDefinitionOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target: Annotated[
        WorkspaceTarget | SelectedUsers | SelectedKeys,
        Field(discriminator="kind", title="Target"),
    ]
    rules: Annotated[
        list[RuleDefinitionOutput],
        Field(
            description="Unordered inline rule definitions; a policy may contain at most one fallback rule",
            max_length=100,
            min_length=1,
            title="Rules",
        ),
    ]


class PolicyEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[UUID, Field(title="Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    name: Annotated[str, Field(max_length=200, min_length=1, title="Name")]
    priority: Annotated[int, Field(ge=0, le=10000, title="Priority")]
    definition: PolicyDefinitionOutput


class PolicyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    name: Annotated[str, Field(title="Name")]
    enabled: Annotated[bool, Field(title="Enabled")]
    priority: Annotated[int, Field(title="Priority")]
    definition: PolicyDefinitionOutput
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class PolicyUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        Name3 | None,
        Field(
            description="Replacement display name; omit to leave unchanged",
            title="Name",
        ),
    ] = None
    enabled: Annotated[
        bool | None,
        Field(
            description="Enable or disable this policy; omit to leave unchanged",
            title="Enabled",
        ),
    ] = None
    priority: Annotated[
        Priority | None,
        Field(
            description="Replacement priority, with lower numbers first; omit to leave unchanged",
            title="Priority",
        ),
    ] = None
    definition: Annotated[
        PolicyDefinitionInput | None,
        Field(description="Replace the complete target and inline rules; omit to leave unchanged"),
    ] = None


class BundleV1(BaseModel):
    """
    A complete, versioned policy snapshot for one organization's model traffic.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[Literal[1], Field(title="Schema Version")] = 1
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    issued_at: Annotated[AwareDatetime, Field(title="Issued At")]
    keys: Annotated[list[KeyEntry], Field(title="Keys")]
    catalog: Catalog
    policies: Annotated[list[PolicyEntry], Field(title="Policies")]


class EnvelopeBundleV1(BaseModel):
    data: BundleV1


class EnvelopeManagementKeyCreatedOut(BaseModel):
    data: ManagementKeyCreatedOut


class EnvelopeManagementKeyOut(BaseModel):
    data: ManagementKeyOut


class EnvelopeOrgServiceAccountCreatedOut(BaseModel):
    data: OrgServiceAccountCreatedOut


class EnvelopePolicyOut(BaseModel):
    data: PolicyOut


class EnvelopeListManagementKeyOut(BaseModel):
    data: Annotated[list[ManagementKeyOut], Field(title="Data")]


class EnvelopeListPolicyOut(BaseModel):
    data: Annotated[list[PolicyOut], Field(title="Data")]


class PolicyBudgetStatus(BaseModel):
    policy: PolicyOut
    computed_at: Annotated[AwareDatetime, Field(title="Computed At")]
    budgets: Annotated[list[BudgetRuleStatus], Field(title="Budgets")]


class PolicyCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the workspace policy",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    enabled: Annotated[
        bool | None,
        Field(
            description="Whether gateways apply this policy after receiving the updated configuration",
            title="Enabled",
        ),
    ] = True
    priority: Annotated[
        int | None,
        Field(
            description="Lower numbers run first; policy ID breaks ties. All matching restrictions apply",
            ge=0,
            le=10000,
            title="Priority",
        ),
    ] = 100
    definition: Annotated[
        PolicyDefinitionInput,
        Field(description="Workspace, user, or inference key target and inline rules"),
    ]


class EnvelopePolicyBudgetStatus(BaseModel):
    data: PolicyBudgetStatus
