# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SecretStr,
)


class AccessKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]
    revoked_at: Annotated[AwareDatetime, Field(title="Revoked At")]


class ActivityOut(BaseModel):
    """
    One audited change, identifying what changed, who changed it, and when.
    """

    id: Annotated[int | None, Field(title="Id")]
    table_name: Annotated[str, Field(title="Table Name")]
    record_id: Annotated[str, Field(title="Record Id")]
    action: Annotated[str, Field(title="Action")]
    user_id: Annotated[str, Field(title="User Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]


class BundleOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    version: Annotated[int, Field(title="Version")]
    issued_at: Annotated[AwareDatetime, Field(title="Issued At")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    signing_key_id: Annotated[str, Field(title="Signing Key Id")]


class ClaimOut(BaseModel):
    claimed: Annotated[bool, Field(title="Claimed")]


class CliAuthApproveIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_code: Annotated[
        str,
        Field(
            description="Device code shown by the CLI",
            max_length=16,
            min_length=8,
            title="User Code",
        ),
    ]
    org_id: Annotated[
        UUID,
        Field(description="Organization the CLI access key should use", title="Org Id"),
    ]


class CliAuthApprovedOut(BaseModel):
    status: Annotated[Literal["approved"], Field(title="Status")]
    client_name: Annotated[str, Field(title="Client Name")]


class CliAuthPollIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    poll_secret: Annotated[
        str,
        Field(
            description="Polling secret returned when device authorization started",
            max_length=256,
            min_length=1,
            title="Poll Secret",
        ),
    ]


class CliAuthPollOut(BaseModel):
    status: Annotated[Literal["pending", "complete"], Field(title="Status")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    token: Annotated[str | None, Field(title="Token")] = None
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    org_name: Annotated[str | None, Field(title="Org Name")] = None


class CliAuthRequestOut(BaseModel):
    client_name: Annotated[str, Field(title="Client Name")]
    requester: Annotated[str, Field(title="Requester")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]


class CliAuthStartIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    client_name: Annotated[
        str,
        Field(
            description="Where the CLI runs, e.g. the hostname; becomes the minted key's label",
            max_length=80,
            min_length=1,
            title="Client Name",
        ),
    ]


class CliAuthStartOut(BaseModel):
    user_code: Annotated[str, Field(title="User Code")]
    verification_url: Annotated[str, Field(title="Verification Url")]
    poll_secret: Annotated[str, Field(title="Poll Secret")]
    interval_seconds: Annotated[int, Field(title="Interval Seconds")]
    expires_in_seconds: Annotated[int, Field(title="Expires In Seconds")]


class DataPlaneInstanceOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    version: Annotated[str, Field(title="Version")]
    bundle_id: Annotated[UUID | None, Field(title="Bundle Id")]
    address: Annotated[str | None, Field(title="Address")]
    status: Annotated[Literal["online", "offline"], Field(title="Status")]
    first_seen: Annotated[AwareDatetime, Field(title="First Seen")]
    last_seen: Annotated[AwareDatetime, Field(title="Last Seen")]


class DeletedOutUUID(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class DeletedOutStr(BaseModel):
    id: Annotated[str, Field(title="Id")]
    deleted_at: Annotated[AwareDatetime, Field(title="Deleted At")]


class EnvelopeAccessKeyRevokedOut(BaseModel):
    data: AccessKeyRevokedOut


class EnvelopeBundleOut(BaseModel):
    data: BundleOut


class EnvelopeClaimOut(BaseModel):
    data: ClaimOut


class EnvelopeCliAuthApprovedOut(BaseModel):
    data: CliAuthApprovedOut


class EnvelopeCliAuthPollOut(BaseModel):
    data: CliAuthPollOut


class EnvelopeCliAuthRequestOut(BaseModel):
    data: CliAuthRequestOut


class EnvelopeCliAuthStartOut(BaseModel):
    data: CliAuthStartOut


class EnvelopeDeletedOutUUID(BaseModel):
    data: DeletedOutUUID


class EnvelopeDeletedOutStr(BaseModel):
    data: DeletedOutStr


class EnvelopeListActivityOut(BaseModel):
    data: Annotated[list[ActivityOut], Field(title="Data")]


class EnvelopeListBundleOut(BaseModel):
    data: Annotated[list[BundleOut], Field(title="Data")]


class EnvelopeListDataPlaneInstanceOut(BaseModel):
    data: Annotated[list[DataPlaneInstanceOut], Field(title="Data")]


class EventsIngestedOut(BaseModel):
    received: Annotated[int, Field(title="Received")]
    ingested: Annotated[int, Field(title="Ingested")]


class HeartbeatOut(BaseModel):
    instance_id: Annotated[UUID, Field(title="Instance Id")]


class HeartbeatV1(BaseModel):
    """
    The identity, software version, and active bundle reported by a data plane.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    instance_id: Annotated[
        UUID,
        Field(
            description="Stable ID for this data-plane installation",
            title="Instance Id",
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="Running data-plane software version",
            max_length=100,
            min_length=1,
            title="Version",
        ),
    ]
    bundle_id: Annotated[
        UUID | None,
        Field(
            description="Policy bundle currently served, if one is loaded",
            title="Bundle Id",
        ),
    ] = None


class InferenceKeyIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[
        str,
        Field(
            description="What this key is for, e.g. staging or the calling app; shown in listings",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]


class InferenceKeyMintedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    token: Annotated[str, Field(title="Token")]


class InferenceKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    revoked: Annotated[bool, Field(title="Revoked")]
    label: Annotated[str, Field(title="Label")]
    prefix: Annotated[str, Field(title="Prefix")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class InferenceKeyRevokedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    status: Annotated[Literal["revoked"], Field(title="Status")]


class InstanceRole(RootModel[Literal["owner", "auditor", "data_plane"]]):
    root: Annotated[Literal["owner", "auditor", "data_plane"], Field(title="InstanceRole")]


class KeyEntry(BaseModel):
    """
    An active inference key included in a policy bundle.

    The bundle contains a token hash for authorization and a key ID for usage attribution, never
    the caller's secret token.
    """

    key_id: Annotated[str, Field(title="Key Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    token_hash: Annotated[str, Field(title="Token Hash")]


class LoginIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        str,
        Field(
            description="Account email address",
            max_length=320,
            min_length=3,
            title="Email",
        ),
    ]
    password: Annotated[
        str,
        Field(
            description="Account password",
            max_length=1024,
            min_length=1,
            title="Password",
        ),
    ]


class MeOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    instance_role: InstanceRole | None
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class ModelEntry(BaseModel):
    """
    A routable model: the caller-facing id plus how to reach and bill it.
    """

    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    upstream_model: Annotated[str, Field(title="Upstream Model")]
    input_price_per_mtok: Annotated[float, Field(title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[float, Field(title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[float, Field(title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[float, Field(title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(title="Context Window")]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")] = None
    capabilities: Annotated[list[str], Field(title="Capabilities")]


class MaxOutputTokens(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Max completion tokens; requests are clamped to it",
            ge=1,
            le=100000000,
            title="Max Output Tokens",
        ),
    ]


class ModelIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model_id: Annotated[
        str,
        Field(
            description="Caller-facing model name",
            max_length=255,
            min_length=1,
            title="Model Id",
        ),
    ]
    provider_id: Annotated[
        str,
        Field(
            description="Provider id the model routes to",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    upstream_model: Annotated[
        str | None,
        Field(
            description="Model name sent to the provider, lets model_id be an alias; defaults to model_id",
            max_length=255,
            title="Upstream Model",
        ),
    ] = ""
    input_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million input tokens",
            ge=0.0,
            title="Input Price Per Mtok",
        ),
    ] = 0.0
    output_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million output tokens",
            ge=0.0,
            title="Output Price Per Mtok",
        ),
    ] = 0.0
    cache_read_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million cache-read input tokens",
            ge=0.0,
            title="Cache Read Price Per Mtok",
        ),
    ] = 0.0
    cache_write_price_per_mtok: Annotated[
        float | None,
        Field(
            description="USD per million cache-write input tokens",
            ge=0.0,
            title="Cache Write Price Per Mtok",
        ),
    ] = 0.0
    context_window: Annotated[
        int | None,
        Field(
            description="Context window in tokens",
            ge=1,
            le=100000000,
            title="Context Window",
        ),
    ] = 128000
    max_output_tokens: Annotated[
        MaxOutputTokens | None,
        Field(
            description="Max completion tokens; requests are clamped to it",
            title="Max Output Tokens",
        ),
    ] = None
    capabilities: Annotated[
        list[str] | None,
        Field(
            description="Capabilities supported by the model",
            max_length=128,
            title="Capabilities",
        ),
    ] = None


class ModelOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    upstream_model: Annotated[str, Field(title="Upstream Model")]
    input_price_per_mtok: Annotated[float, Field(title="Input Price Per Mtok")]
    output_price_per_mtok: Annotated[float, Field(title="Output Price Per Mtok")]
    cache_read_price_per_mtok: Annotated[float, Field(title="Cache Read Price Per Mtok")]
    cache_write_price_per_mtok: Annotated[float, Field(title="Cache Write Price Per Mtok")]
    context_window: Annotated[int, Field(title="Context Window")]
    max_output_tokens: Annotated[int | None, Field(title="Max Output Tokens")]
    capabilities: Annotated[list[str], Field(title="Capabilities")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class OrgCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Org name, e.g. My Org",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class OrgOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    personal_for: Annotated[UUID | None, Field(title="Personal For")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class OrgRole(RootModel[Literal["owner", "admin", "member", "data_plane"]]):
    root: Annotated[Literal["owner", "admin", "member", "data_plane"], Field(title="OrgRole")]


class Name(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Replacement organization name",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class OrgUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[Name | None, Field(description="Replacement organization name", title="Name")] = None


class PasswordChangeIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    current_password: Annotated[
        str,
        Field(
            description="Current account password",
            max_length=1024,
            min_length=1,
            title="Current Password",
        ),
    ]
    new_password: Annotated[
        str,
        Field(
            description="Replacement password; at least 8 characters",
            max_length=1024,
            min_length=8,
            title="New Password",
        ),
    ]


class PasswordChangedOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    status: Annotated[Literal["changed"], Field(title="Status")]


class Permission(
    RootModel[
        Literal[
            "organizations.read",
            "organizations.create",
            "organizations.update",
            "organizations.delete",
            "principals.read",
            "principals.manage",
            "members.read",
            "members.manage",
            "workspaces.read",
            "workspaces.create",
            "workspaces.update",
            "workspaces.delete",
            "catalog.read",
            "catalog.manage",
            "provider-credentials.read",
            "provider-credentials.manage",
            "inference-keys.read",
            "inference-keys.manage",
            "bundles.read",
            "bundles.publish",
            "usage.read",
            "usage.ingest",
            "data-planes.read",
            "data-planes.heartbeat",
            "audit.read",
            "access-keys.read",
            "access-keys.issue",
            "access-keys.revoke",
        ]
    ]
):
    root: Annotated[
        Literal[
            "organizations.read",
            "organizations.create",
            "organizations.update",
            "organizations.delete",
            "principals.read",
            "principals.manage",
            "members.read",
            "members.manage",
            "workspaces.read",
            "workspaces.create",
            "workspaces.update",
            "workspaces.delete",
            "catalog.read",
            "catalog.manage",
            "provider-credentials.read",
            "provider-credentials.manage",
            "inference-keys.read",
            "inference-keys.manage",
            "bundles.read",
            "bundles.publish",
            "usage.read",
            "usage.ingest",
            "data-planes.read",
            "data-planes.heartbeat",
            "audit.read",
            "access-keys.read",
            "access-keys.issue",
            "access-keys.revoke",
        ],
        Field(title="Permission"),
    ]


class ProviderCredentialIn(BaseModel):
    """
    A provider API key and the metadata used to select it.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Annotated[
        str,
        Field(
            description="Provider name from the catalog, e.g. openai",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider",
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Handle for this key within the provider and scope, e.g. prod or backup",
            max_length=80,
            min_length=1,
            pattern="^[A-Za-z0-9][A-Za-z0-9_.-]*$",
            title="Name",
        ),
    ] = "default"
    value: Annotated[
        SecretStr,
        Field(
            description="The provider API key; stored securely and never returned",
            max_length=16384,
            min_length=1,
            title="Value",
        ),
    ]
    priority: Annotated[
        int | None,
        Field(
            description="Lower is tried first; ties break by name",
            ge=0,
            le=1000000,
            title="Priority",
        ),
    ] = 100


class ProviderCredentialOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    provider_id: Annotated[UUID, Field(title="Provider Id")]
    provider_name: Annotated[str, Field(title="Provider Name")]
    name: Annotated[str, Field(title="Name")]
    priority: Annotated[int, Field(title="Priority")]
    enabled: Annotated[bool, Field(title="Enabled")]
    version: Annotated[int, Field(title="Version")]
    status: Annotated[str, Field(title="Status")]
    status_at: Annotated[AwareDatetime | None, Field(title="Status At")]
    fingerprint: Annotated[str, Field(title="Fingerprint")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    scope: Annotated[Literal["platform", "org", "workspace"], Field(title="Scope")]


class Priority(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description="Replacement selection priority; lower values are tried first",
            ge=0,
            le=1000000,
            title="Priority",
        ),
    ]


class ProviderCredentialUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    priority: Annotated[
        Priority | None,
        Field(
            description="Replacement selection priority; lower values are tried first",
            title="Priority",
        ),
    ] = None
    enabled: Annotated[
        bool | None,
        Field(
            description="Whether the credential may be selected for requests",
            title="Enabled",
        ),
    ] = None


class ProviderCredentialValueIn(BaseModel):
    """
    A rotation: the same credential, a new value.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    value: Annotated[
        SecretStr,
        Field(
            description="The replacement provider API key",
            max_length=16384,
            min_length=1,
            title="Value",
        ),
    ]


class ProviderEntry(BaseModel):
    """
    An upstream LLM provider endpoint and its supported request parameters.
    """

    provider_id: Annotated[str, Field(title="Provider Id")]
    kind: Annotated[Literal["openai_compatible", "anthropic"], Field(title="Kind")]
    base_url: Annotated[AnyUrl, Field(title="Base Url")]
    param_aliases: Annotated[dict[str, str] | None, Field(title="Param Aliases")] = None
    accepted_params: Annotated[list[str] | None, Field(title="Accepted Params")] = None
    params_closed: Annotated[bool | None, Field(title="Params Closed")] = False


class AcceptedParams(RootModel[list[str]]):
    root: Annotated[
        list[str],
        Field(
            description="Params known accepted beyond the core; consulted when params_closed",
            max_length=256,
            title="Accepted Params",
        ),
    ]


class ProviderIn(BaseModel):
    """
    An upstream provider endpoint and its request-profile settings.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    provider_id: Annotated[
        str,
        Field(
            description="Provider name, e.g. openai",
            max_length=63,
            min_length=1,
            pattern="^[a-z0-9][a-z0-9_-]*$",
            title="Provider Id",
        ),
    ]
    kind: Annotated[
        Literal["openai_compatible", "anthropic"] | None,
        Field(description="Adapter kind", title="Kind"),
    ] = "openai_compatible"
    base_url: Annotated[
        AnyUrl,
        Field(
            description="OpenAI-compatible endpoint, e.g. https://api.groq.com/openai/v1",
            title="Base Url",
        ),
    ]
    icon: Annotated[
        str | None,
        Field(
            description="Provider mark as a standalone 24x24 SVG document, or an empty string when no icon is available. Clients must sanitize this untrusted markup before rendering it",
            max_length=65536,
            title="Icon",
        ),
    ] = ""
    param_aliases: Annotated[
        dict[str, str] | None,
        Field(
            description="Canonical param name to this provider's spelling",
            max_length=256,
            title="Param Aliases",
        ),
    ] = None
    accepted_params: Annotated[
        AcceptedParams | None,
        Field(
            description="Params known accepted beyond the core; consulted when params_closed",
            title="Accepted Params",
        ),
    ] = None
    params_closed: Annotated[
        bool | None,
        Field(
            description="True when the provider's request schema rejects unknown params",
            title="Params Closed",
        ),
    ] = False


class ProviderOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    kind: Annotated[str, Field(title="Kind")]
    base_url: Annotated[str, Field(title="Base Url")]
    icon: Annotated[str, Field(title="Icon")]
    param_aliases: Annotated[dict[str, str], Field(title="Param Aliases")]
    accepted_params: Annotated[list[str] | None, Field(title="Accepted Params")]
    params_closed: Annotated[bool, Field(title="Params Closed")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class QuickstartIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: Annotated[
        str,
        Field(
            description="Existing limited access key for the first data plane",
            max_length=512,
            min_length=1,
            title="Token",
        ),
    ]


class QuickstartOut(BaseModel):
    path: Annotated[str, Field(title="Path")]


class ScopeLevel(RootModel[Literal["instance", "org", "workspace"]]):
    root: Annotated[Literal["instance", "org", "workspace"], Field(title="ScopeLevel")]


class SecretPurpose(RootModel[Literal["provider"]]):
    root: Annotated[
        Literal["provider"],
        Field(
            description="The kind of credential addressed by a secret reference.",
            title="SecretPurpose",
        ),
    ]


class SecretRef(BaseModel):
    """
    A stable reference to a secret value and the scope that owns it.
    """

    purpose: SecretPurpose
    service: Annotated[str, Field(title="Service")]
    name: Annotated[str, Field(title="Name")]
    secret_id: Annotated[UUID, Field(title="Secret Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")] = None


class ServiceAccountIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the service account",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    instance_role: Annotated[
        InstanceRole | None,
        Field(description="Optional instance-wide role for the service account"),
    ] = None


class SignupIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        str,
        Field(
            description="Email address for the new account",
            max_length=320,
            min_length=3,
            title="Email",
        ),
    ]
    name: Annotated[
        str | None,
        Field(
            description="Display name; defaults to the email address",
            max_length=200,
            title="Name",
        ),
    ] = ""
    password: Annotated[
        str,
        Field(
            description="Password for the new account; at least 8 characters",
            max_length=1024,
            min_length=8,
            title="Password",
        ),
    ]


class TaxonomyOut(BaseModel):
    providers: Annotated[list[ProviderOut], Field(title="Providers")]
    models: Annotated[list[ModelOut], Field(title="Models")]


class UsageEventOut(BaseModel):
    event_id: Annotated[UUID, Field(title="Event Id")]
    request_id: Annotated[UUID, Field(title="Request Id")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    key_id: Annotated[str, Field(title="Key Id")]
    model_id: Annotated[str, Field(title="Model Id")]
    provider_id: Annotated[str, Field(title="Provider Id")]
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]
    cost_usd: Annotated[float, Field(title="Cost Usd")]
    cost_input_usd: Annotated[float, Field(title="Cost Input Usd")]
    cost_output_usd: Annotated[float, Field(title="Cost Output Usd")]
    cache_read_tokens: Annotated[int, Field(title="Cache Read Tokens")]
    cache_write_tokens: Annotated[int, Field(title="Cache Write Tokens")]
    latency_ms: Annotated[int, Field(title="Latency Ms")]
    status: Annotated[str, Field(title="Status")]
    stream: Annotated[bool, Field(title="Stream")]
    credential_id: Annotated[UUID | None, Field(title="Credential Id")]
    credential_scope: Annotated[str | None, Field(title="Credential Scope")]


class UsageEventV1(BaseModel):
    """
    One metered model request reported by a data plane.

    `event_id` makes retries idempotent.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        Literal[1],
        Field(description="Usage event schema version", title="Schema Version"),
    ] = 1
    event_id: Annotated[UUID, Field(description="Idempotency key for event ingestion", title="Event Id")]
    request_id: Annotated[UUID, Field(description="Data-plane request ID", title="Request Id")]
    occurred_at: Annotated[
        AwareDatetime,
        Field(description="Timestamp when the request completed", title="Occurred At"),
    ]
    org_id: Annotated[UUID, Field(description="Organization that made the request", title="Org Id")]
    workspace_id: Annotated[UUID, Field(description="Workspace that made the request", title="Workspace Id")]
    key_id: Annotated[
        str,
        Field(
            description="Inference key ID used for the request",
            max_length=255,
            min_length=1,
            title="Key Id",
        ),
    ]
    model_id: Annotated[
        str,
        Field(
            description="Caller-facing model ID",
            max_length=255,
            min_length=1,
            title="Model Id",
        ),
    ]
    provider_id: Annotated[
        str,
        Field(
            description="Provider that served the request, or empty for an early denial",
            max_length=63,
            title="Provider Id",
        ),
    ]
    bundle_id: Annotated[UUID, Field(description="Policy bundle used for the request", title="Bundle Id")]
    input_tokens: Annotated[
        int,
        Field(description="Total input tokens", ge=0, le=2147483647, title="Input Tokens"),
    ]
    output_tokens: Annotated[
        int,
        Field(
            description="Total output tokens",
            ge=0,
            le=2147483647,
            title="Output Tokens",
        ),
    ]
    cost_usd: Annotated[
        float,
        Field(description="Total estimated cost in USD", ge=0.0, title="Cost Usd"),
    ]
    cost_input_usd: Annotated[
        float | None,
        Field(description="Estimated input cost in USD", ge=0.0, title="Cost Input Usd"),
    ] = 0.0
    cost_output_usd: Annotated[
        float | None,
        Field(description="Estimated output cost in USD", ge=0.0, title="Cost Output Usd"),
    ] = 0.0
    cache_read_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens read from a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Read Tokens",
        ),
    ] = 0
    cache_write_tokens: Annotated[
        int | None,
        Field(
            description="Input tokens written to a provider cache",
            ge=0,
            le=2147483647,
            title="Cache Write Tokens",
        ),
    ] = 0
    latency_ms: Annotated[
        int,
        Field(
            description="End-to-end request latency in milliseconds",
            ge=0,
            le=2147483647,
            title="Latency Ms",
        ),
    ]
    status: Annotated[
        Literal[
            "ok",
            "upstream_error",
            "denied",
            "timeout",
            "cancelled",
            "credential_rejected",
            "rate_limited",
        ],
        Field(
            description="How the request ended; cancelled events may contain partial token counts",
            title="Status",
        ),
    ]
    stream: Annotated[bool, Field(description="Whether the response was streamed", title="Stream")]
    credential_id: Annotated[
        UUID | None,
        Field(
            description="Provider credential used for the request",
            title="Credential Id",
        ),
    ] = None
    credential_scope: Annotated[
        Literal["platform", "org", "workspace"] | None,
        Field(
            description="Scope of the provider credential used for the request",
            title="Credential Scope",
        ),
    ] = None


class UserOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    instance_role: Annotated[str | None, Field(title="Instance Role")]
    service_account: Annotated[bool, Field(title="Service Account")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    orgs: Annotated[list[UUID], Field(title="Orgs")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Any | None, Field(title="Input")] = None
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None


class WorkspaceCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Workspace name, e.g. Staging",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    slug: Annotated[
        str | None,
        Field(
            description="Workspace handle, unique in the org and usable in place of the id; derived from the name when omitted",
            max_length=63,
            pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$",
            title="Slug",
        ),
    ] = ""


class WorkspaceOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    name: Annotated[str, Field(title="Name")]
    slug: Annotated[str, Field(title="Slug")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]


class WorkspaceRole(RootModel[Literal["admin", "member", "viewer"]]):
    root: Annotated[Literal["admin", "member", "viewer"], Field(title="WorkspaceRole")]


class Name1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Replacement workspace name",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]


class WorkspaceUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[Name1 | None, Field(description="Replacement workspace name", title="Name")] = None


class AccessKeyIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[
        str,
        Field(
            description="Where this key lives, such as ci, laptop, or data-plane",
            max_length=80,
            min_length=1,
            title="Label",
        ),
    ]
    user_id: Annotated[
        UUID | None,
        Field(
            description="Principal the key authenticates; defaults to the authenticated principal",
            title="User Id",
        ),
    ] = None
    permissions: Annotated[
        list[Permission],
        Field(
            description="Explicit maximum permissions carried by the key",
            min_length=1,
            title="Permissions",
        ),
    ]
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Optional expiration timestamp with a timezone",
            title="Expires At",
        ),
    ] = None


class CredentialEntry(BaseModel):
    """
    A provider credential reference, priority, and version included in a policy bundle.

    The secret value is not included. A version change tells data planes to refresh their cached value.
    """

    ref: SecretRef
    priority: Annotated[int, Field(title="Priority")]
    version: Annotated[int, Field(title="Version")]


class EnrollOut(BaseModel):
    orgs: Annotated[list[OrgOut], Field(title="Orgs")]
    personal_org_id: Annotated[UUID | None, Field(title="Personal Org Id")]


class EnvelopeEnrollOut(BaseModel):
    data: EnrollOut


class EnvelopeEventsIngestedOut(BaseModel):
    data: EventsIngestedOut


class EnvelopeHeartbeatOut(BaseModel):
    data: HeartbeatOut


class EnvelopeInferenceKeyMintedOut(BaseModel):
    data: InferenceKeyMintedOut


class EnvelopeInferenceKeyRevokedOut(BaseModel):
    data: InferenceKeyRevokedOut


class EnvelopeMeOut(BaseModel):
    data: MeOut


class EnvelopeModelOut(BaseModel):
    data: ModelOut


class EnvelopeOrgOut(BaseModel):
    data: OrgOut


class EnvelopePasswordChangedOut(BaseModel):
    data: PasswordChangedOut


class EnvelopeProviderCredentialOut(BaseModel):
    data: ProviderCredentialOut


class EnvelopeProviderOut(BaseModel):
    data: ProviderOut


class EnvelopeQuickstartOut(BaseModel):
    data: QuickstartOut


class EnvelopeTaxonomyOut(BaseModel):
    data: TaxonomyOut


class EnvelopeUserOut(BaseModel):
    data: UserOut


class EnvelopeWorkspaceOut(BaseModel):
    data: WorkspaceOut


class EnvelopeListInferenceKeyOut(BaseModel):
    data: Annotated[list[InferenceKeyOut], Field(title="Data")]


class EnvelopeListOrgOut(BaseModel):
    data: Annotated[list[OrgOut], Field(title="Data")]


class EnvelopeListProviderCredentialOut(BaseModel):
    data: Annotated[list[ProviderCredentialOut], Field(title="Data")]


class EnvelopeListUsageEventOut(BaseModel):
    data: Annotated[list[UsageEventOut], Field(title="Data")]


class EnvelopeListUserOut(BaseModel):
    data: Annotated[list[UserOut], Field(title="Data")]


class EnvelopeListWorkspaceOut(BaseModel):
    data: Annotated[list[WorkspaceOut], Field(title="Data")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class MembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    role: OrgRole
    status: Annotated[Literal["member"], Field(title="Status")]


class OrgMemberOut(BaseModel):
    """
    A human user or service account that belongs to an organization.
    """

    user_id: Annotated[UUID, Field(title="User Id")]
    email: Annotated[str, Field(title="Email")]
    name: Annotated[str, Field(title="Name")]
    service_account: Annotated[bool, Field(title="Service Account")]
    role: OrgRole
    status: Annotated[Literal["member"], Field(title="Status")]


class OrgMembershipIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[OrgRole, Field(description="Organization role to grant")]


class Scope(BaseModel):
    level: ScopeLevel
    org_id: Annotated[UUID | None, Field(title="Org Id")] = None
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")] = None


class WorkspaceMembershipIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[WorkspaceRole, Field(description="Workspace role to grant")]


class WorkspaceMembershipOut(BaseModel):
    user_id: Annotated[UUID, Field(title="User Id")]
    workspace_id: Annotated[UUID, Field(title="Workspace Id")]
    role: WorkspaceRole
    status: Annotated[Literal["member"], Field(title="Status")]


class AccessKeyMintedOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    prefix: Annotated[str, Field(title="Prefix")]
    permissions: Annotated[list[Permission], Field(title="Permissions")]
    label: Annotated[str, Field(title="Label")]
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")]
    revoked_at: Annotated[AwareDatetime | None, Field(title="Revoked At")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    scope: Scope
    status: Annotated[Literal["active", "expired", "revoked"], Field(title="Status")]
    token: Annotated[str, Field(title="Token")]


class AccessKeyOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    user_id: Annotated[UUID, Field(title="User Id")]
    org_id: Annotated[UUID | None, Field(title="Org Id")]
    workspace_id: Annotated[UUID | None, Field(title="Workspace Id")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    prefix: Annotated[str, Field(title="Prefix")]
    permissions: Annotated[list[Permission], Field(title="Permissions")]
    label: Annotated[str, Field(title="Label")]
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")]
    revoked_at: Annotated[AwareDatetime | None, Field(title="Revoked At")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    deleted_at: Annotated[AwareDatetime | None, Field(title="Deleted At")]
    scope: Scope
    status: Annotated[Literal["active", "expired", "revoked"], Field(title="Status")]


class Catalog(BaseModel):
    """
    Everything routable in one org: providers, the models that point at them, and the credentials
    they are reached with.
    """

    providers: Annotated[list[ProviderEntry], Field(title="Providers")]
    models: Annotated[list[ModelEntry], Field(title="Models")]
    credentials: Annotated[list[CredentialEntry] | None, Field(title="Credentials", validate_default=True)] = []


class EnvelopeAccessKeyMintedOut(BaseModel):
    data: AccessKeyMintedOut


class EnvelopeMembershipOut(BaseModel):
    data: MembershipOut


class EnvelopeWorkspaceMembershipOut(BaseModel):
    data: WorkspaceMembershipOut


class EnvelopeListAccessKeyOut(BaseModel):
    data: Annotated[list[AccessKeyOut], Field(title="Data")]


class EnvelopeListOrgMemberOut(BaseModel):
    data: Annotated[list[OrgMemberOut], Field(title="Data")]


class EnvelopeListWorkspaceMembershipOut(BaseModel):
    data: Annotated[list[WorkspaceMembershipOut], Field(title="Data")]


class BundleV1(BaseModel):
    """
    A complete, versioned policy snapshot for one organization's model traffic.
    """

    schema_version: Annotated[Literal[1], Field(title="Schema Version")] = 1
    bundle_id: Annotated[UUID, Field(title="Bundle Id")]
    org_id: Annotated[UUID, Field(title="Org Id")]
    issued_at: Annotated[AwareDatetime, Field(title="Issued At")]
    expires_at: Annotated[AwareDatetime, Field(title="Expires At")]
    keys: Annotated[list[KeyEntry], Field(title="Keys")]
    catalog: Catalog


class SignedBundle(BaseModel):
    """
    A BundleV1 as it crosses the wire and rests on disk.

    A bundle that fails verification is rejected and the previous one keeps serving.
    """

    payload: BundleV1
    signature: Annotated[str, Field(title="Signature")]
    signing_key_id: Annotated[str, Field(title="Signing Key Id")]


class EnvelopeSignedBundle(BaseModel):
    data: SignedBundle
