"""Generate the repo's applied taxonomy.yml from the researched catalog.

taxonomy/ holds both halves: the researched catalog, and taxonomy.yml, the applied file
`airllmcp taxonomy` reads. This turns the first into
the second, so the applied catalog is derived rather than hand-maintained and drifting.

    uv run python build_taxonomy.py            write taxonomy/taxonomy.yml
    uv run python build_taxonomy.py --check    fail if it is out of date, for CI

Only validated providers are emitted. A candidate has no base_url and no model catalog, so
there is nothing to apply.

## Ordering

The output is reviewed in a diff, so every ordering is fixed and total:

  providers   sorted by provider_id
  models      sorted by (provider_id, model_id)
  keys        a declared order, identical for every entry

Nothing is emitted in dict-insertion or filesystem order, and the file is written only when
its content actually changes, so a no-op run leaves the mtime alone.

## upstream_model is what goes on the wire, and is not always the catalog id

Fireworks accepts only the fully qualified accounts/fireworks/models/<name> for some of its
models, so its source sets upstream_id and this prefers it. A source that does not set one
sends the catalog id unchanged.

## Model ids are always provider-prefixed

`gpt-oss-120b` is served by Groq and Together at different prices and limits, so a bare id
cannot be the caller-facing key. Prefixing only on collision would be worse: adding a
provider would silently rename models that already exist and break callers. So every
model_id is `<provider>/<upstream>`, and upstream_model carries the name to send on the
wire. Adding a provider can then never rename anything.

## What is dropped, and why

A model marked unreachable by smoke.py is skipped. The catalog then holds what a provider
advertises, and the applied taxonomy holds what actually answered, which is the number that
matters for routing. Together advertises 74 chat models and serves 23; the rest need a
dedicated endpoint provisioned.

A model with no context window is skipped. ModelIn defaults context_window to 128000, and
emitting that default for a model whose real window is unknown would be inventing a routing
limit. Skipping is honest and visible in the run summary.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from adapter_support import supported_capabilities, supported_modalities
from capability_support import resolve_capabilities, resolve_input_modalities, resolve_output_modalities
from catalog_io import atomic_write_text
from evidence import REACHABILITY_DEFINITIVE, REACHABILITY_PROBE_VERSION, target_fingerprint
from parameter_support import resolve_parameter_support
from paths import TAXONOMY
from provider_profile import SurfaceProfile, provider_surfaces

APPLIED = TAXONOMY / "taxonomy.yml"

HEADER = """\
# Applied model taxonomy. Generated by the provider-catalog skill from taxonomy/; do not
# hand-edit, your change will be overwritten on the next run.
#
#   .agents/skills/provider-catalog/scripts/build_taxonomy.py
#
# Providers and models both come from live vendor APIs. Prices are USD per million tokens.
# model_id is always <provider>/<upstream> so that adding a provider can never rename a
# model that already exists; upstream_model is what goes on the wire.
"""


def selected_surface(provider: dict, model: dict) -> SurfaceProfile | None:
    surfaces = provider_surfaces(provider)
    status = model.get("endpoint_status") or {}
    current = {
        surface.endpoint: status.get(surface.endpoint)
        for surface in surfaces
        if (status.get(surface.endpoint) or {}).get("version") == REACHABILITY_PROBE_VERSION
        and (status.get(surface.endpoint) or {}).get("target")
        == target_fingerprint(provider, model, surface.endpoint, "reachability", REACHABILITY_PROBE_VERSION)
    }
    proven = [surface for surface in surfaces if (current.get(surface.endpoint) or {}).get("outcome") == "ok"]
    if proven:
        return sorted(proven, key=lambda surface: (surface.endpoint != "responses", surfaces.index(surface)))[0]
    if len(current) == len(surfaces) and all((status or {}).get("outcome") in REACHABILITY_DEFINITIVE for status in current.values()):
        return None
    return surfaces[0]


def build() -> tuple[dict, list[str], list[str]]:
    providers = yaml.safe_load((TAXONOMY / "providers.yml").read_text())["providers"]
    providers = sorted(providers, key=lambda p: p["id"])

    emitted_providers, emitted_models, skipped, unreachable = [], [], [], []
    for provider in providers:
        icon = TAXONOMY / "icons" / f"{provider['icon_mono']}.svg"
        default_surface = provider_surfaces(provider)[0]
        emitted_providers.append(
            {
                "provider_id": provider["id"],
                "kind": default_surface.egress_kind,
                "base_url": provider["base_url"],
                "icon": icon.read_text().strip() if icon.exists() else "",
            }
        )

        catalog = TAXONOMY / "models" / f"{provider['id']}.json"
        if not catalog.exists():
            continue
        for model in json.loads(catalog.read_text())["models"]:
            if model.get("reachable") is False:
                unreachable.append(f"{provider['id']}/{model['id']}")
                continue
            if not model.get("context_length"):
                skipped.append(f"{provider['id']}/{model['id']}")
                continue
            surface = selected_surface(provider, model)
            if surface is None:
                unreachable.append(f"{provider['id']}/{model['id']}")
                continue
            price = model.get("pricing") or {}
            parameter_support = resolve_parameter_support(model.get("parameter_evidence") or {}, surface.endpoint)
            input_modalities = supported_modalities(surface.egress_kind, resolve_input_modalities(model, surface.endpoint))
            output_modalities = supported_modalities(surface.egress_kind, resolve_output_modalities(model), output=True)
            capabilities = supported_capabilities(surface.egress_kind, resolve_capabilities(model, surface.endpoint))
            emitted_models.append(
                {
                    "model_id": f"{provider['id']}/{model['id']}",
                    "provider_id": provider["id"],
                    "upstream_model": model.get("upstream_id") or model["id"],
                    "input_price_per_mtok": float(price.get("input_per_mtok") or 0.0),
                    "output_price_per_mtok": float(price.get("output_per_mtok") or 0.0),
                    "cache_read_price_per_mtok": float(price.get("cached_input_per_mtok") or 0.0),
                    "cache_write_price_per_mtok": float(price.get("cache_write_per_mtok") or 0.0),
                    "context_window": int(model["context_length"]),
                    "max_output_tokens": model.get("max_output_tokens"),
                    "input_modalities": input_modalities,
                    "output_modalities": output_modalities,
                    "capabilities": capabilities,
                    **({"parameter_support": parameter_support} if parameter_support else {}),
                    **({"egress_kind": surface.egress_kind} if surface.egress_kind != default_surface.egress_kind else {}),
                }
            )

    emitted_models.sort(key=lambda m: (m["provider_id"], m["model_id"]))
    return {"providers": emitted_providers, "models": emitted_models}, skipped, unreachable


def render(spec: dict) -> str:
    return HEADER + yaml.safe_dump(spec, sort_keys=False, width=200, allow_unicode=True, default_flow_style=False)


def main() -> int:
    spec, skipped, unreachable = build()
    text = render(spec)
    check = "--check" in sys.argv

    current = APPLIED.read_text() if APPLIED.exists() else ""
    if check:
        if current != text:
            print("taxonomy.yml is out of date; run build_taxonomy.py")
            return 1
        print(f"taxonomy.yml is current: {len(spec['providers'])} providers, {len(spec['models'])} models")
        return 0

    if current == text:
        print(f"taxonomy.yml unchanged: {len(spec['providers'])} providers, {len(spec['models'])} models")
    else:
        atomic_write_text(APPLIED, text)
        print(f"wrote {APPLIED.name}: {len(spec['providers'])} providers, {len(spec['models'])} models")
    if unreachable:
        print(
            f"  {len(unreachable)} skipped as unreachable, proven by smoke.py: {', '.join(unreachable[:4])}{' ...' if len(unreachable) > 4 else ''}"
        )
    if skipped:
        print(f"  {len(skipped)} skipped for having no context window: {', '.join(skipped[:4])}{' ...' if len(skipped) > 4 else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
