"""Generate the repo's applied taxonomy.yml from the researched catalog.

taxonomy/ holds both halves: the researched catalog, and taxonomy.yml, the applied file
`airllmcp taxonomy` reads. This turns the first into
the second, so the applied catalog is derived rather than hand-maintained and drifting.

    uv run python build_taxonomy.py            write taxonomy/taxonomy.yml
    uv run python build_taxonomy.py --check    fail if it is out of date, for CI

Only validated providers are emitted. A candidate has no base_url and no model catalog, so
there is nothing to apply.

## Ordering

The output is reviewed in a diff, so every ordering is fixed and total:

  providers   sorted by provider_id
  models      sorted by (provider_id, model_id)
  keys        a declared order, identical for every entry

Nothing is emitted in dict-insertion or filesystem order, and the file is written only when
its content actually changes, so a no-op run leaves the mtime alone.

## Model ids are always provider-prefixed

`gpt-oss-120b` is served by Groq and Together at different prices and limits, so a bare id
cannot be the caller-facing key. Prefixing only on collision would be worse: adding a
provider would silently rename models that already exist and break callers. So every
model_id is `<provider>/<upstream>`, and upstream_model carries the name to send on the
wire. Adding a provider can then never rename anything.

## What is dropped, and why

A model with no context window is skipped. ModelIn defaults context_window to 128000, and
emitting that default for a model whose real window is unknown would be inventing a routing
limit. Skipping is honest and visible in the run summary.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import TAXONOMY

APPLIED = TAXONOMY / "taxonomy.yml"
KIND = {"anthropic": "anthropic"}          # everything else is openai_compatible

HEADER = """\
# Applied model taxonomy. Generated by the provider-catalog skill from taxonomy/; do not
# hand-edit, your change will be overwritten on the next run.
#
#   .agents/skills/provider-catalog/scripts/build_taxonomy.py
#
# Providers and models both come from live vendor APIs. Prices are USD per million tokens.
# model_id is always <provider>/<upstream> so that adding a provider can never rename a
# model that already exists; upstream_model is what goes on the wire.
"""


def capabilities(model: dict) -> list[str]:
    """The vocabulary the applied taxonomy already uses: streaming, tools, vision."""
    caps = ["streaming"]
    if model.get("supports_tools"):
        caps.append("tools")
    if "image" in (model.get("input_modalities") or []):
        caps.append("vision")
    return caps


def build() -> tuple[dict, list[str]]:
    providers = yaml.safe_load((TAXONOMY / "providers.yml").read_text())["providers"]
    providers = sorted(providers, key=lambda p: p["id"])

    emitted_providers, emitted_models, skipped = [], [], []
    for provider in providers:
        icon = TAXONOMY / "icons" / f"{provider['icon_mono']}.svg"
        emitted_providers.append({
            "provider_id": provider["id"],
            "kind": KIND.get(provider["id"], "openai_compatible"),
            "base_url": provider["base_url"],
            "icon": icon.read_text().strip() if icon.exists() else "",
        })

        catalog = TAXONOMY / "models" / f"{provider['id']}.json"
        if not catalog.exists():
            continue
        for model in json.loads(catalog.read_text())["models"]:
            if not model.get("context_length"):
                skipped.append(f"{provider['id']}/{model['id']}")
                continue
            price = model.get("pricing") or {}
            emitted_models.append({
                "model_id": f"{provider['id']}/{model['id']}",
                "provider_id": provider["id"],
                "upstream_model": model["id"],
                "input_price_per_mtok": float(price.get("input_per_mtok") or 0.0),
                "output_price_per_mtok": float(price.get("output_per_mtok") or 0.0),
                "cache_read_price_per_mtok": float(price.get("cached_input_per_mtok") or 0.0),
                "cache_write_price_per_mtok": float(price.get("cache_write_per_mtok") or 0.0),
                "context_window": int(model["context_length"]),
                "max_output_tokens": model.get("max_output_tokens"),
                "capabilities": capabilities(model),
            })

    emitted_models.sort(key=lambda m: (m["provider_id"], m["model_id"]))
    return {"providers": emitted_providers, "models": emitted_models}, skipped


def render(spec: dict) -> str:
    return HEADER + yaml.safe_dump(spec, sort_keys=False, width=200, allow_unicode=True, default_flow_style=False)


def main() -> int:
    spec, skipped = build()
    text = render(spec)
    check = "--check" in sys.argv

    current = APPLIED.read_text() if APPLIED.exists() else ""
    if check:
        if current != text:
            print("taxonomy.yml is out of date; run build_taxonomy.py")
            return 1
        print(f"taxonomy.yml is current: {len(spec['providers'])} providers, {len(spec['models'])} models")
        return 0

    if current == text:
        print(f"taxonomy.yml unchanged: {len(spec['providers'])} providers, {len(spec['models'])} models")
    else:
        APPLIED.write_text(text)
        print(f"wrote {APPLIED.name}: {len(spec['providers'])} providers, {len(spec['models'])} models")
    if skipped:
        print(f"  {len(skipped)} models skipped for having no context window: {', '.join(skipped[:5])}"
              f"{' ...' if len(skipped) > 5 else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
