from __future__ import annotations

import json
from collections import defaultdict
from decimal import Decimal
from gzip import compress
from typing import TYPE_CHECKING, cast

import yaml

from airmux_runtime.taxonomy import dump_taxonomy
from contract import MODALITIES, Modality
from contract.money import parse_fixed_point
from model_audit.cases import load_cases, load_features
from model_audit.evidence import write_behavior
from model_audit.surfaces import discover

if TYPE_CHECKING:
    from pathlib import Path

    from model_audit.models import BehaviorRecord

CAPABILITY_PROJECTION = {
    "reasoning": "reasoning",
    "streaming": "streaming",
    "structured_output": "structured_output",
    "tool_calling": "tools",
}
CAPABILITY_NAMES = frozenset(CAPABILITY_PROJECTION.values())
MODALITY_PROJECTION: dict[str, tuple[str, Modality]] = {
    "input_text": ("input", "text"),
    "input_image": ("input", "image"),
    "input_pdf": ("input", "pdf"),
    "output_text": ("output", "text"),
}
HEADER = """\
# Applied model taxonomy. Generated by model-audit; do not edit directly.
#
#   uv run airmux-audit taxonomy build
#
# Behavioral fields merge provider catalog evidence with promoted direct API observations.
"""


def _rate(value: object) -> Decimal:
    if value is None:
        return Decimal(0)
    if isinstance(value, Decimal):
        return value
    if isinstance(value, int) and not isinstance(value, bool):
        return Decimal(value)
    if isinstance(value, str):
        return parse_fixed_point(value)
    message = "catalog pricing must use exact decimals"
    raise TypeError(message)


def _behaviors(root: Path) -> tuple[BehaviorRecord, ...]:
    project = root / "model-audit"
    cases = tuple(load_cases(project / "cases", load_features(project / "definitions" / "features.yml")))
    behavior = write_behavior(root / "model-audit" / "evidence" / "accepted.json", root / "taxonomy" / "behavior.json", cases)
    return behavior.behaviors


def _model_routes(taxonomy: Path) -> dict[str, str]:
    document = yaml.safe_load((taxonomy / "model-routes.yml").read_text(encoding="utf-8"))
    return {str(model_id): str(surface) for model_id, surface in (document.get("models") or {}).items()}


def _surface(provider: dict, model_id: str, routes: dict[str, str]) -> str:
    return routes.get(model_id, str(provider["primary_surface"]))


def _projected_capabilities(behavior: BehaviorRecord) -> frozenset[str]:
    names = behavior.claim.name.split("+")
    projected = {CAPABILITY_PROJECTION.get(name, name) for name in names if name in CAPABILITY_PROJECTION or name in CAPABILITY_NAMES}
    return frozenset(projected)


def _capabilities(model: dict, behaviors: list[BehaviorRecord]) -> list[str]:
    capabilities = {"streaming"}
    if model.get("supports_tools") is True:
        capabilities.add("tools")
    if model.get("supports_structured_output") is True:
        capabilities.add("structured_output")
    if model.get("supports_thinking") is True:
        capabilities.add("reasoning")
    for behavior in behaviors:
        projected = _projected_capabilities(behavior)
        if behavior.verdict == "supported":
            capabilities.update(projected)
        elif behavior.verdict == "unsupported" and not behavior.claim.profile and len(projected) == 1:
            capabilities.difference_update(projected)
    return sorted(capabilities)


def _modalities(
    model: dict,
    behaviors: list[BehaviorRecord],
    *,
    model_id: str = "model",
) -> tuple[list[Modality], list[Modality]]:
    projected: dict[str, set[Modality]] = {
        "input": set(model.get("input_modalities") or []),
        "output": set(model.get("output_modalities") or []),
    }
    for behavior in behaviors:
        projection = MODALITY_PROJECTION.get(behavior.claim.name)
        if projection is None or behavior.claim.profile or behavior.verdict == "unknown":
            continue
        direction, modality = projection
        if behavior.verdict == "supported":
            projected[direction].add(modality)
        elif behavior.verdict == "unsupported":
            projected[direction].discard(modality)
    ordered = {direction: [modality for modality in MODALITIES if modality in projected[direction]] for direction in projected}
    missing = [f"{direction}_modalities" for direction in ("input", "output") if not ordered[direction]]
    if missing:
        message = f"{model_id} is missing required {', '.join(missing)}"
        raise ValueError(message)
    return ordered["input"], ordered["output"]


def _parameter_support(model: dict, endpoint: str, behaviors: list[BehaviorRecord]) -> dict[str, str]:
    discovery = (((model.get("parameter_evidence") or {}).get("model_discovery") or {}).get("support") or {}).get(endpoint) or {}
    statuses: dict[str, set[str]] = defaultdict(set)
    broad_unsupported = set()
    for behavior in behaviors:
        if behavior.claim.dimension == "option":
            statuses[behavior.claim.name].add(behavior.verdict)
            if behavior.verdict == "unsupported" and not behavior.claim.profile:
                broad_unsupported.add(behavior.claim.name)
    resolved = {name: status for name, status in discovery.items() if status == "supported"}
    for name, values in statuses.items():
        if "supported" in values:
            resolved[name] = "supported"
        elif name in broad_unsupported and values == {"unsupported"}:
            resolved[name] = "unsupported"
    return dict(sorted(resolved.items()))


def _provider_entry(provider: dict, icon: str) -> dict[str, object]:
    default_surface = str(provider["primary_surface"])
    kind = str(provider.get("egress_kind") or discover()[default_surface].kind)
    profile = {field: provider[field] for field in ("param_aliases", "params_closed", "accepted_params") if field in provider}
    return {
        "provider_id": provider["id"],
        "kind": kind,
        "base_url": provider["base_url"],
        "icon": icon,
        **profile,
    }


def build(root: Path) -> dict[str, list[dict[str, object]]]:
    taxonomy = root / "taxonomy"
    provider_document = yaml.safe_load((taxonomy / "providers.yml").read_text(encoding="utf-8"))
    providers = sorted(provider_document["providers"], key=lambda provider: provider["id"])
    routes = _model_routes(taxonomy)
    routed_models = set()
    behavior_by_model: dict[str, list[BehaviorRecord]] = defaultdict(list)
    for behavior in _behaviors(root):
        behavior_by_model[behavior.model_id].append(behavior)
    emitted_providers = []
    emitted_models = []
    for provider in providers:
        provider_id = provider["id"]
        default_surface = str(provider["primary_surface"])
        icon_path = taxonomy / "icons" / f"{provider['icon_mono']}.svg"
        emitted_providers.append(_provider_entry(provider, icon_path.read_text(encoding="utf-8").strip() if icon_path.exists() else ""))
        models_path = taxonomy / "models" / f"{provider_id}.json"
        if not models_path.exists():
            continue
        for model in json.loads(models_path.read_text(encoding="utf-8"), parse_float=Decimal).get("models", []):
            if not model.get("context_length"):
                continue
            model_id = f"{provider_id}/{model['id']}"
            behaviors = behavior_by_model[model_id]
            surface = _surface(provider, model_id, routes)
            if surface not in provider["ingress"]:
                message = f"{model_id} routes through {surface}, which {provider_id} does not expose"
                raise ValueError(message)
            if model_id in routes:
                routed_models.add(model_id)
            surface_behaviors = [behavior for behavior in behaviors if behavior.surface_id == surface]
            input_modalities, output_modalities = _modalities(model, surface_behaviors, model_id=model_id)
            price = model.get("pricing") or {}
            codecs = discover()
            kind = str(provider.get("egress_kind") or codecs[surface].kind)
            emitted_models.append(
                {
                    "model_id": model_id,
                    "provider_id": provider_id,
                    "upstream_model": model.get("upstream_id") or model["id"],
                    "input_price_per_mtok": _rate(price.get("input_per_mtok")),
                    "output_price_per_mtok": _rate(price.get("output_per_mtok")),
                    "cache_read_price_per_mtok": _rate(price.get("cached_input_per_mtok")),
                    "cache_write_price_per_mtok": _rate(price.get("cache_write_per_mtok")),
                    "context_window": int(model["context_length"]),
                    "max_output_tokens": cast("int | None", model.get("max_output_tokens")),
                    "input_modalities": input_modalities,
                    "output_modalities": output_modalities,
                    "capabilities": _capabilities(model, surface_behaviors),
                    **({"parameter_support": support} if (support := _parameter_support(model, codecs[surface].endpoint, surface_behaviors)) else {}),
                    **({"egress_kind": kind} if kind != str(provider.get("egress_kind") or codecs[default_surface].kind) else {}),
                }
            )
    emitted_models.sort(key=lambda model: (str(model["provider_id"]), str(model["model_id"])))
    if unknown_routes := sorted(set(routes) - routed_models):
        message = f"model routes name unknown models: {', '.join(unknown_routes)}"
        raise ValueError(message)
    return {"providers": emitted_providers, "models": emitted_models}


def render(specification: dict[str, list[dict[str, object]]]) -> str:
    return HEADER + dump_taxonomy(specification)


def write(root: Path, *, check: bool = False) -> tuple[int, int, bool]:
    specification = build(root)
    text = render(specification)
    taxonomy_path = root / "taxonomy" / "taxonomy.yml"
    resource_path = root / "apps" / "data-plane" / "src" / "data_plane" / "resources" / "taxonomy.yml.gz"
    resource = compress(text.encode("utf-8"), mtime=0)
    changed = (
        not taxonomy_path.exists()
        or taxonomy_path.read_text(encoding="utf-8") != text
        or not resource_path.exists()
        or resource_path.read_bytes() != resource
    )
    if check:
        return len(specification["providers"]), len(specification["models"]), changed
    if not taxonomy_path.exists() or taxonomy_path.read_text(encoding="utf-8") != text:
        taxonomy_path.write_text(text, encoding="utf-8")
    if not resource_path.exists() or resource_path.read_bytes() != resource:
        resource_path.parent.mkdir(parents=True, exist_ok=True)
        resource_path.write_bytes(resource)
    return len(specification["providers"]), len(specification["models"]), changed
