from __future__ import annotations

import json
from collections import defaultdict
from typing import TYPE_CHECKING, cast

import yaml

from model_audit.cases import load_cases, load_features
from model_audit.evidence import write_behavior
from model_audit.surfaces import discover

if TYPE_CHECKING:
    from pathlib import Path

    from model_audit.models import BehaviorRecord

CAPABILITY_PROJECTION = {
    "reasoning": "reasoning",
    "streaming": "streaming",
    "structured_output": "structured_output",
    "text_generation": "text",
    "tool_calling": "tools",
}
HEADER = """\
# Applied model taxonomy. Generated by model-audit; do not edit directly.
#
#   uv run airllm-audit taxonomy build
#
# Behavioral fields merge provider catalog evidence with promoted direct API observations.
"""


def _behaviors(root: Path) -> tuple[BehaviorRecord, ...]:
    project = root / "model-audit"
    cases = tuple(load_cases(project / "cases", load_features(project / "definitions" / "features.yml")))
    behavior = write_behavior(root / "model-audit" / "evidence" / "accepted.json", root / "taxonomy" / "behavior.json", cases)
    return behavior.behaviors


def _surface(provider: dict, behaviors: list[BehaviorRecord]) -> str:
    codecs = discover()
    observed = sorted({behavior.surface_id for behavior in behaviors}, key=lambda surface: codecs[surface].priority if surface in codecs else 99)
    if observed:
        return observed[0]
    return str(provider["primary_surface"])


def _capabilities(model: dict, behaviors: list[BehaviorRecord]) -> list[str]:
    capabilities = {"streaming"}
    if model.get("supports_tools") is True:
        capabilities.add("tools")
    if model.get("supports_structured_output") is True:
        capabilities.add("structured_output")
    if model.get("supports_thinking") is True:
        capabilities.add("reasoning")
    modalities = set(model.get("input_modalities") or [])
    if "image" in modalities:
        capabilities.add("vision")
    if "pdf" in modalities:
        capabilities.add("pdf")
    for behavior in behaviors:
        projected = CAPABILITY_PROJECTION.get(behavior.claim.name)
        if behavior.claim.name == "input_image":
            projected = "vision"
        elif behavior.claim.name == "input_pdf":
            projected = "pdf"
        if projected is not None and behavior.verdict == "supported":
            capabilities.add(projected)
        elif projected is not None and behavior.verdict == "unsupported" and not behavior.claim.profile:
            capabilities.discard(projected)
    return sorted(capabilities)


def _parameter_support(model: dict, endpoint: str, behaviors: list[BehaviorRecord]) -> dict[str, str]:
    discovery = (((model.get("parameter_evidence") or {}).get("model_discovery") or {}).get("support") or {}).get(endpoint) or {}
    statuses: dict[str, set[str]] = defaultdict(set)
    broad_unsupported = set()
    for behavior in behaviors:
        if behavior.claim.dimension == "option":
            statuses[behavior.claim.name].add(behavior.verdict)
            if behavior.verdict == "unsupported" and not behavior.claim.profile:
                broad_unsupported.add(behavior.claim.name)
    resolved = {name: status for name, status in discovery.items() if status == "supported"}
    for name, values in statuses.items():
        if "supported" in values:
            resolved[name] = "supported"
        elif name in broad_unsupported and values == {"unsupported"}:
            resolved[name] = "unsupported"
    return dict(sorted(resolved.items()))


def _provider_entry(provider: dict, icon: str) -> dict[str, object]:
    default_surface = str(provider["primary_surface"])
    profile = {field: provider[field] for field in ("param_aliases", "params_closed", "accepted_params") if field in provider}
    return {
        "provider_id": provider["id"],
        "kind": discover()[default_surface].kind,
        "base_url": provider["base_url"],
        "icon": icon,
        **profile,
    }


def build(root: Path) -> dict[str, list[dict[str, object]]]:
    taxonomy = root / "taxonomy"
    provider_document = yaml.safe_load((taxonomy / "providers.yml").read_text(encoding="utf-8"))
    providers = sorted(provider_document["providers"], key=lambda provider: provider["id"])
    behavior_by_model: dict[str, list[BehaviorRecord]] = defaultdict(list)
    for behavior in _behaviors(root):
        behavior_by_model[behavior.model_id].append(behavior)
    emitted_providers = []
    emitted_models = []
    for provider in providers:
        provider_id = provider["id"]
        default_surface = str(provider["primary_surface"])
        icon_path = taxonomy / "icons" / f"{provider['icon_mono']}.svg"
        emitted_providers.append(_provider_entry(provider, icon_path.read_text(encoding="utf-8").strip() if icon_path.exists() else ""))
        models_path = taxonomy / "models" / f"{provider_id}.json"
        if not models_path.exists():
            continue
        for model in json.loads(models_path.read_text(encoding="utf-8")).get("models", []):
            if not model.get("context_length"):
                continue
            model_id = f"{provider_id}/{model['id']}"
            behaviors = behavior_by_model[model_id]
            surface = _surface(provider, behaviors)
            surface_behaviors = [behavior for behavior in behaviors if behavior.surface_id == surface]
            price = model.get("pricing") or {}
            codecs = discover()
            kind = codecs[surface].kind
            emitted_models.append(
                {
                    "model_id": model_id,
                    "provider_id": provider_id,
                    "upstream_model": model.get("upstream_id") or model["id"],
                    "input_price_per_mtok": float(price.get("input_per_mtok") or 0),
                    "output_price_per_mtok": float(price.get("output_per_mtok") or 0),
                    "cache_read_price_per_mtok": float(price.get("cached_input_per_mtok") or 0),
                    "cache_write_price_per_mtok": float(price.get("cache_write_per_mtok") or 0),
                    "context_window": int(model["context_length"]),
                    "max_output_tokens": cast("int | None", model.get("max_output_tokens")),
                    "capabilities": _capabilities(model, surface_behaviors),
                    **({"parameter_support": support} if (support := _parameter_support(model, codecs[surface].endpoint, surface_behaviors)) else {}),
                    **({"egress_kind": kind} if kind != codecs[default_surface].kind else {}),
                }
            )
    emitted_models.sort(key=lambda model: (str(model["provider_id"]), str(model["model_id"])))
    return {"providers": emitted_providers, "models": emitted_models}


def render(specification: dict[str, list[dict[str, object]]]) -> str:
    return HEADER + yaml.safe_dump(specification, sort_keys=False, width=200, allow_unicode=True)


def write(root: Path, *, check: bool = False) -> tuple[int, int, bool]:
    specification = build(root)
    text = render(specification)
    path = root / "taxonomy" / "taxonomy.yml"
    changed = not path.exists() or path.read_text(encoding="utf-8") != text
    if check:
        return len(specification["providers"]), len(specification["models"]), changed
    if changed:
        path.write_text(text, encoding="utf-8")
    return len(specification["providers"]), len(specification["models"]), changed
