"""Regenerate seed.yml from the live catalog.

seed.yml is the bootstrap copy of the irreplaceable half of the catalog: which providers
exist and where their facts live. Everything else under taxonomy/ is derived from it and
can be thrown away.

It is generated rather than hand-maintained so it cannot drift from providers.yml in
silence, and validate.py fails when the two disagree.

    Generated as part of `uv run airmux-audit providers sync`.
"""

from __future__ import annotations

import yaml

from .outcomes import CatalogCount, SeedWritten
from .paths import TAXONOMY

SEED = TAXONOMY.parent / "model-audit" / "catalog" / "seed.yml"
# schema is omitted: it is derived by extract_schemas.py and doc_schemas.py from openapi
CARRIED = (
    "id",
    "name",
    "icon_mono",
    "icon_color",
    "homepage",
    "docs",
    "base_url",
    "openapi",
    "models_url",
    "ingress",
    "primary_surface",
    "egress_kind",
    "auth",
    "env_var",
)

HEADER = """\
# Bootstrap seed for the provider catalog. Generated by airmux-audit; do not hand-edit.
#
# This is the half of taxonomy/ that cannot be regenerated: the list of providers and the
# addresses of their facts. Schemas, model lists, icons and reports are all derived from
# these fields, so taxonomy/ can be deleted and rebuilt from this file alone.
#
# Every field means what it means in providers.yml. schema is deliberately absent, since
# it is produced from openapi.
"""


def strip(entries: list[dict]) -> list[dict]:
    return [{k: e[k] for k in CARRIED if k in e} for e in entries]


def build() -> dict:
    out = {}
    for filename, key in (("providers.yml", "providers"), ("routers.yml", "routers")):
        path = TAXONOMY / filename
        if path.exists():
            out[key] = strip(yaml.safe_load(path.read_text())[key])
    # candidates are already identity-only; carry them verbatim so a rebuild keeps the list
    path = TAXONOMY / "candidates.yml"
    if path.exists():
        out["candidates"] = yaml.safe_load(path.read_text())["candidates"]
    return out


def run() -> SeedWritten:
    seed = build()
    SEED.write_text(HEADER + yaml.safe_dump(seed, sort_keys=False, width=100, allow_unicode=True))
    return SeedWritten(SEED, tuple(CatalogCount(kind, len(seed[kind])) for kind in ("providers", "routers", "candidates") if kind in seed))
