from __future__ import annotations

import os
from pathlib import Path

import typer
import uvicorn
import yaml

from data_plane.canonical import json_schemas

app = typer.Typer(name="airllmdp")

GENERATED_HEADER = "# Generated by `airllmdp schema`; never hand-edit.\n"


@app.command()
def serve(host: str = "127.0.0.1", port: int = 8080, dev: bool = False, config: str = "airllm.yml", workers: int = 1) -> None:
    os.environ["GW_CONFIG"] = config
    if dev:
        os.environ["GW_DEV"] = "1"
    # Workers share one cache dir: the SQLite outbox serializes their writes and one leaseholder flushes.
    uvicorn.run("data_plane.app:app", host=host, port=port, reload=dev, workers=None if dev else workers)


@app.command()
def schema(out: Path = Path("taxonomy/schemas/completion")) -> None:
    """Export the completion definition as JSON Schema in YAML; CI re-exports and fails on drift."""
    out.mkdir(parents=True, exist_ok=True)
    for face, spec in json_schemas().items():
        path = out / f"airllm.{face}.yaml"
        path.write_text(GENERATED_HEADER + yaml.safe_dump(spec, sort_keys=False, width=150), encoding="utf-8")
        typer.echo(f"wrote {path}")
