from __future__ import annotations

import os
from pathlib import Path
from typing import Annotated

import typer
import uvicorn
import yaml

from data_plane.canonical import json_schemas
from data_plane.setup import initialize, validate_local

app = typer.Typer(name="tokkeeper-data-plane", help="Run an LLM gateway with a local taxonomy or a connected control plane.", no_args_is_help=True)

GENERATED_HEADER = "# Generated by `tokkeeper-data-plane schema`; never hand-edit.\n"


@app.command(rich_help_panel="Resources")
def serve(host: str = "127.0.0.1", port: int = 8080, dev: bool = False, config: str = "tokkeeper.yml", workers: int = 1) -> None:
    os.environ["TOKKEEPER_CONFIG"] = config
    if dev:
        os.environ["TOKKEEPER_DEV"] = "1"
    # Workers share one cache dir: the SQLite outbox serializes their writes and one leaseholder flushes.
    uvicorn.run("data_plane.app:load_app", host=host, port=port, reload=dev, workers=None if dev else workers, factory=True)


@app.command(rich_help_panel="Setup")
def init(
    taxonomy: Annotated[Path, typer.Option("--taxonomy", exists=True, dir_okay=False, readable=True, help="Existing taxonomy YAML file")],
    directory: Annotated[Path, typer.Option("--directory", help="New private directory for configuration and the inference key")] = Path("gateway"),
) -> None:
    """Initialize a gateway without a database or control plane."""
    try:
        initialize(directory, taxonomy)
    except (OSError, TypeError, ValueError, yaml.YAMLError) as error:
        raise typer.BadParameter(str(error)) from error
    typer.echo(
        f"Created {directory}. Set TOKKEEPER_INFERENCE_KEY from {directory / 'inference.key'}, then validate and serve {directory / 'tokkeeper.yml'}."
    )


@app.command(rich_help_panel="Testing")
def validate(config: Annotated[Path, typer.Option("--config", exists=True, dir_okay=False)] = Path("tokkeeper.yml")) -> None:
    """Validate local configuration, taxonomy, keys, and policies without contacting providers."""
    try:
        validate_local(config)
    except (OSError, TypeError, ValueError, yaml.YAMLError) as error:
        raise typer.BadParameter(str(error)) from error
    typer.echo("Gateway configuration is valid. Provider credentials and connectivity are checked when serving requests.")


@app.command(rich_help_panel="Testing")
def schema(out: Path = Path("taxonomy/schemas/completion")) -> None:
    """Export the completion definition as JSON Schema in YAML; CI re-exports and fails on drift."""
    out.mkdir(parents=True, exist_ok=True)
    for face, spec in json_schemas().items():
        path = out / f"tokkeeper.{face}.yaml"
        path.write_text(GENERATED_HEADER + yaml.safe_dump(spec, sort_keys=False, width=150), encoding="utf-8")
        typer.echo(f"wrote {path}")
