from __future__ import annotations

import os
from typing import TYPE_CHECKING, Literal

import uvicorn
import yaml

from data_plane.canonical import json_schemas
from data_plane.robyn_server import serve_robyn

if TYPE_CHECKING:
    from pathlib import Path

GENERATED_HEADER = "# Generated by `airmux gateway schema`; never hand-edit.\n"


def serve(  # noqa: PLR0913 -- server selection extends the existing gateway serve options
    config: Path,
    *,
    host: str,
    port: int,
    dev: bool,
    workers: int,
    server: Literal["uvicorn", "robyn"] = "uvicorn",
) -> None:
    os.environ["AIRMUX_CONFIG"] = str(config)
    if dev:
        os.environ["AIRMUX_DEV"] = "1"
    if server == "robyn":
        serve_robyn(host=host, port=port, workers=workers)
        return
    uvicorn.run("data_plane.app:load_app", host=host, port=port, reload=dev, workers=None if dev else workers, factory=True, access_log=dev)


def export_schema(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for face, schema in json_schemas().items():
        (directory / f"airmux.{face}.yaml").write_text(GENERATED_HEADER + yaml.safe_dump(schema, sort_keys=False, width=150), encoding="utf-8")
