from __future__ import annotations

import os
from typing import TYPE_CHECKING

import uvicorn
import yaml

from data_plane.canonical import json_schemas

if TYPE_CHECKING:
    from pathlib import Path

GENERATED_HEADER = "# Generated by `tokkeeper gateway schema`; never hand-edit.\n"


def serve(config: Path, *, host: str, port: int, dev: bool, workers: int) -> None:
    os.environ["TOKKEEPER_CONFIG"] = str(config)
    if dev:
        os.environ["TOKKEEPER_DEV"] = "1"
    else:
        os.environ.pop("TOKKEEPER_DEV", None)
    uvicorn.run("data_plane.app:load_app", host=host, port=port, reload=dev, workers=None if dev else workers, factory=True)


def export_schema(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for face, schema in json_schemas().items():
        (directory / f"tokkeeper.{face}.yaml").write_text(GENERATED_HEADER + yaml.safe_dump(schema, sort_keys=False, width=150), encoding="utf-8")
