# generated by datamodel-codegen:
#   filename:  airllm-openapi.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class ApiKeyOut(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    user_id: str = Field(..., title="User Id")
    disabled: bool = Field(..., title="Disabled")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class BundleOut(BaseModel):
    id: UUID = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    version: int = Field(..., title="Version")
    issued_at: AwareDatetime = Field(..., title="Issued At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    signing_key_id: str = Field(..., title="Signing Key Id")


class CompileOut(BaseModel):
    bundle_id: str = Field(..., title="Bundle Id")
    version: int = Field(..., title="Version")


class DataPlaneInstanceOut(BaseModel):
    instance_id: str = Field(..., title="Instance Id")
    org_id: str | None = Field(..., title="Org Id")
    version: str = Field(..., title="Version")
    bundle_id: UUID | None = Field(..., title="Bundle Id")
    address: str | None = Field(..., title="Address")
    status: Literal["online", "offline"] = Field(..., title="Status")
    first_seen: AwareDatetime = Field(..., title="First Seen")
    last_seen: AwareDatetime = Field(..., title="Last Seen")


class DeletedOutStr(BaseModel):
    id: str = Field(..., title="Id")
    deleted_at: AwareDatetime = Field(..., title="Deleted At")


class DiscoverIn(BaseModel):
    email: str = Field(..., title="Email")


class DiscoverOut(BaseModel):
    method: Literal["password", "sso"] = Field(..., title="Method")
    connection_id: str | None = Field(None, title="Connection Id")


class EnvelopeCompileOut(BaseModel):
    data: CompileOut


class EnvelopeDeletedOutStr(BaseModel):
    data: DeletedOutStr


class EnvelopeDiscoverOut(BaseModel):
    data: DiscoverOut


class EnvelopeListApiKeyOut(BaseModel):
    data: list[ApiKeyOut] = Field(..., title="Data")


class EnvelopeListBundleOut(BaseModel):
    data: list[BundleOut] = Field(..., title="Data")


class EnvelopeListDataPlaneInstanceOut(BaseModel):
    data: list[DataPlaneInstanceOut] = Field(..., title="Data")


class EventsIngestedOut(BaseModel):
    received: int = Field(..., title="Received")
    ingested: int = Field(..., title="Ingested")


class HeartbeatOut(BaseModel):
    instance_id: str = Field(..., title="Instance Id")


class HeartbeatV1(BaseModel):
    """
    A data plane announcing itself to the control plane; the record survives, liveness is derived from last_seen.
    """

    instance_id: str = Field(..., title="Instance Id")
    version: str = Field(..., title="Version")
    org_id: str | None = Field(None, title="Org Id")
    bundle_id: UUID | None = Field(None, title="Bundle Id")


class KeyEntry(BaseModel):
    """
    An API key as the data plane sees it: enough to authorize with zero I/O.

    The caller's bearer is an opaque secret; the data plane hashes it (see
    credentials.py) and looks the hash up here. Absence is invalidity, so
    revocation is simply dropping out of the next bundle. key_id exists for
    event attribution only. The bundle carries hashes of live secrets and
    stays org-sensitive even though the hashes are not reversible.
    """

    key_id: str = Field(..., title="Key Id")
    org_id: str = Field(..., title="Org Id")
    token_hash: str = Field(..., title="Token Hash")


class KeyOut(BaseModel):
    key_id: str = Field(..., title="Key Id")
    token: str = Field(..., title="Token")


class KeyRevokedOut(BaseModel):
    key_id: str = Field(..., title="Key Id")
    status: Literal["revoked"] = Field(..., title="Status")


class LoginIn(BaseModel):
    email: str = Field(..., title="Email")
    password: str = Field(..., title="Password")


class MeOut(BaseModel):
    user_id: str = Field(..., title="User Id")
    email: str = Field(..., title="Email")
    name: str = Field(..., title="Name")
    instance_admin: bool = Field(..., title="Instance Admin")
    orgs: list[str] = Field(..., title="Orgs")


class MembershipOut(BaseModel):
    user_id: str = Field(..., title="User Id")
    org_id: str = Field(..., title="Org Id")
    status: Literal["member"] = Field(..., title="Status")


class MgmtTokenOut(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str | None = Field(..., title="Org Id")
    user_id: str = Field(..., title="User Id")
    revoked: bool = Field(..., title="Revoked")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class MintedTokenOut(BaseModel):
    token_id: str = Field(..., title="Token Id")
    org_id: str | None = Field(..., title="Org Id")
    user_id: str = Field(..., title="User Id")
    token: str = Field(..., title="Token")


class ModelEntry(BaseModel):
    """
    A routable model: the caller-facing id plus how to reach and bill it.
    """

    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    upstream_model: str = Field(..., title="Upstream Model")
    input_price_per_mtok: float = Field(..., title="Input Price Per Mtok")
    output_price_per_mtok: float = Field(..., title="Output Price Per Mtok")
    context_window: int = Field(..., title="Context Window")
    max_output_tokens: int | None = Field(None, title="Max Output Tokens")
    capabilities: list[str] = Field(..., title="Capabilities")


class ModelIn(BaseModel):
    model_id: str = Field(..., description="Caller-facing model id", title="Model Id")
    provider_id: str = Field(..., description="Provider id the model routes to", title="Provider Id")
    upstream_model: str | None = Field(
        "",
        description="Model name sent to the provider, lets model_id be an alias; defaults to model_id",
        title="Upstream Model",
    )
    input_price_per_mtok: float | None = Field(0.0, description="USD per million input tokens", title="Input Price Per Mtok")
    output_price_per_mtok: float | None = Field(0.0, description="USD per million output tokens", title="Output Price Per Mtok")
    context_window: int | None = Field(128000, description="Context window in tokens", title="Context Window")
    max_output_tokens: int | None = Field(
        None,
        description="Max completion tokens; requests are clamped to it",
        title="Max Output Tokens",
    )
    capabilities: list[str] | None = Field(
        ["streaming", "tools"],
        description="Capabilities, comma separated",
        title="Capabilities",
    )


class ModelOut(BaseModel):
    id: str = Field(..., title="Id")
    provider_id: str = Field(..., title="Provider Id")
    upstream_model: str = Field(..., title="Upstream Model")
    input_price_per_mtok: float = Field(..., title="Input Price Per Mtok")
    output_price_per_mtok: float = Field(..., title="Output Price Per Mtok")
    context_window: int = Field(..., title="Context Window")
    max_output_tokens: int | None = Field(..., title="Max Output Tokens")
    capabilities: list[str] = Field(..., title="Capabilities")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class OrgCreate(BaseModel):
    id: str = Field(..., description="Org id, e.g. org-dev", title="Id")
    name: str | None = Field("", description="Display name, defaults to the id", title="Name")


class OrgOut(BaseModel):
    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class OrgPatch(BaseModel):
    name: str | None = Field(None, title="Name")


class PasswordChangeIn(BaseModel):
    current_password: str = Field(..., title="Current Password")
    new_password: str = Field(..., title="New Password")


class PasswordChangedOut(BaseModel):
    user_id: str = Field(..., title="User Id")
    status: Literal["changed"] = Field(..., title="Status")


class PasswordSetIn(BaseModel):
    password: str = Field(..., title="Password")


class PasswordSetOut(BaseModel):
    user_id: str = Field(..., title="User Id")
    status: Literal["set"] = Field(..., title="Status")


class ProviderEntry(BaseModel):
    """
    An upstream LLM provider endpoint.
    """

    provider_id: str = Field(..., title="Provider Id")
    kind: Literal["openai_compatible", "anthropic"] = Field(..., title="Kind")
    base_url: AnyUrl = Field(..., title="Base Url")
    credential_ref: str = Field(..., title="Credential Ref")
    cache_read_multiplier: float | None = Field(1.0, title="Cache Read Multiplier")
    cache_write_multiplier: float | None = Field(1.0, title="Cache Write Multiplier")


class ProviderIn(BaseModel):
    provider_id: str = Field(..., description="Provider id, e.g. openai", title="Provider Id")
    kind: Literal["openai_compatible", "anthropic"] | None = Field("openai_compatible", description="Adapter kind", title="Kind")
    base_url: str = Field(
        ...,
        description="OpenAI-compatible endpoint, e.g. https://api.groq.com/openai/v1",
        title="Base Url",
    )
    credential_ref: str = Field(
        ...,
        description="env: or file: reference resolved by the data plane, never a raw secret",
        title="Credential Ref",
    )
    cache_read_multiplier: float | None = Field(
        1.0,
        description="Input price factor for prompt-cache hits",
        title="Cache Read Multiplier",
    )
    cache_write_multiplier: float | None = Field(
        1.0,
        description="Input price factor for cache writes",
        title="Cache Write Multiplier",
    )


class ProviderOut(BaseModel):
    id: str = Field(..., title="Id")
    kind: str = Field(..., title="Kind")
    base_url: str = Field(..., title="Base Url")
    credential_ref: str = Field(..., title="Credential Ref")
    cache_read_multiplier: float = Field(..., title="Cache Read Multiplier")
    cache_write_multiplier: float = Field(..., title="Cache Write Multiplier")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class ServiceAccountIn(BaseModel):
    name: str = Field(
        ...,
        description="Service account name; the email is derived as name-<id>@airbytesvcaccount.ai",
        title="Name",
    )
    instance_admin: bool | None = Field(
        False,
        description="Whether the service account administers the whole instance",
        title="Instance Admin",
    )


class SsoConnectionIn(BaseModel):
    issuer: str = Field(..., title="Issuer")
    client_id: str = Field(..., title="Client Id")
    client_secret: str = Field(..., title="Client Secret")
    email_domains: list[str] = Field(..., title="Email Domains")
    jit: bool | None = Field(False, title="Jit")


class SsoConnectionOut(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    issuer: str = Field(..., title="Issuer")
    client_id: str = Field(..., title="Client Id")
    email_domains: list[str] = Field(..., title="Email Domains")
    jit: bool = Field(..., title="Jit")
    authorization_endpoint: str = Field(..., title="Authorization Endpoint")
    token_endpoint: str = Field(..., title="Token Endpoint")
    jwks_uri: str = Field(..., title="Jwks Uri")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")


class SsoStartIn(BaseModel):
    connection_id: str = Field(..., title="Connection Id")


class SsoStartOut(BaseModel):
    authorize_url: str = Field(..., title="Authorize Url")


class TaxonomyOut(BaseModel):
    providers: list[ProviderOut] = Field(..., title="Providers")
    models: list[ModelOut] = Field(..., title="Models")


class TokenRevokedOut(BaseModel):
    token_id: str = Field(..., title="Token Id")
    status: Literal["revoked"] = Field(..., title="Status")


class UsageEventOut(BaseModel):
    event_id: UUID = Field(..., title="Event Id")
    request_id: str = Field(..., title="Request Id")
    occurred_at: AwareDatetime = Field(..., title="Occurred At")
    org_id: str = Field(..., title="Org Id")
    key_id: str = Field(..., title="Key Id")
    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    bundle_id: UUID = Field(..., title="Bundle Id")
    input_tokens: int = Field(..., title="Input Tokens")
    output_tokens: int = Field(..., title="Output Tokens")
    cost_usd: float = Field(..., title="Cost Usd")
    cost_input_usd: float = Field(..., title="Cost Input Usd")
    cost_output_usd: float = Field(..., title="Cost Output Usd")
    cache_read_tokens: int = Field(..., title="Cache Read Tokens")
    cache_write_tokens: int = Field(..., title="Cache Write Tokens")
    latency_ms: int = Field(..., title="Latency Ms")
    status: str = Field(..., title="Status")
    stream: bool = Field(..., title="Stream")


class UsageEventV1(BaseModel):
    """
    One metered request, emitted by the data plane and ingested by the control plane.

    Delivery is at-least-once from a local disk buffer; the control plane upserts on
    event_id, so replays after an outage land exactly once.
    """

    schema_version: Literal[1] = Field(1, title="Schema Version")
    event_id: UUID = Field(..., title="Event Id")
    request_id: str = Field(..., title="Request Id")
    occurred_at: AwareDatetime = Field(..., title="Occurred At")
    org_id: str = Field(..., title="Org Id")
    key_id: str = Field(..., title="Key Id")
    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    bundle_id: UUID = Field(..., title="Bundle Id")
    input_tokens: int = Field(..., title="Input Tokens")
    output_tokens: int = Field(..., title="Output Tokens")
    cost_usd: float = Field(..., title="Cost Usd")
    cost_input_usd: float | None = Field(0.0, title="Cost Input Usd")
    cost_output_usd: float | None = Field(0.0, title="Cost Output Usd")
    cache_read_tokens: int | None = Field(0, title="Cache Read Tokens")
    cache_write_tokens: int | None = Field(0, title="Cache Write Tokens")
    latency_ms: int = Field(..., title="Latency Ms")
    status: Literal["ok", "upstream_error", "denied", "timeout", "cancelled"] = Field(..., title="Status")
    stream: bool = Field(..., title="Stream")


class UserCreate(BaseModel):
    email: str = Field(..., description="Unique email identifying the user", title="Email")
    name: str | None = Field("", description="Display name, defaults to the email", title="Name")
    instance_admin: bool | None = Field(
        False,
        description="Whether the user administers the whole instance",
        title="Instance Admin",
    )


class UserOut(BaseModel):
    id: str = Field(..., title="Id")
    email: str = Field(..., title="Email")
    name: str = Field(..., title="Name")
    instance_admin: bool = Field(..., title="Instance Admin")
    service_account: bool = Field(..., title="Service Account")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    deleted_at: AwareDatetime | None = Field(..., title="Deleted At")
    orgs: list[str] = Field(..., title="Orgs")


class UserTokenIn(BaseModel):
    org_id: str | None = Field(
        None,
        description="Org to scope the token to; omit for an instance token, instance admins only",
        title="Org Id",
    )


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class Catalog(BaseModel):
    """
    Everything routable in one org: providers and the models that point at them.
    """

    providers: list[ProviderEntry] = Field(..., title="Providers")
    models: list[ModelEntry] = Field(..., title="Models")


class EnvelopeEventsIngestedOut(BaseModel):
    data: EventsIngestedOut


class EnvelopeHeartbeatOut(BaseModel):
    data: HeartbeatOut


class EnvelopeKeyOut(BaseModel):
    data: KeyOut


class EnvelopeKeyRevokedOut(BaseModel):
    data: KeyRevokedOut


class EnvelopeMeOut(BaseModel):
    data: MeOut


class EnvelopeMembershipOut(BaseModel):
    data: MembershipOut


class EnvelopeMintedTokenOut(BaseModel):
    data: MintedTokenOut


class EnvelopeModelOut(BaseModel):
    data: ModelOut


class EnvelopeOrgOut(BaseModel):
    data: OrgOut


class EnvelopePasswordChangedOut(BaseModel):
    data: PasswordChangedOut


class EnvelopePasswordSetOut(BaseModel):
    data: PasswordSetOut


class EnvelopeProviderOut(BaseModel):
    data: ProviderOut


class EnvelopeSsoConnectionOut(BaseModel):
    data: SsoConnectionOut


class EnvelopeSsoStartOut(BaseModel):
    data: SsoStartOut


class EnvelopeTaxonomyOut(BaseModel):
    data: TaxonomyOut


class EnvelopeTokenRevokedOut(BaseModel):
    data: TokenRevokedOut


class EnvelopeUserOut(BaseModel):
    data: UserOut


class EnvelopeListMgmtTokenOut(BaseModel):
    data: list[MgmtTokenOut] = Field(..., title="Data")


class EnvelopeListOrgOut(BaseModel):
    data: list[OrgOut] = Field(..., title="Data")


class EnvelopeListSsoConnectionOut(BaseModel):
    data: list[SsoConnectionOut] = Field(..., title="Data")


class EnvelopeListUsageEventOut(BaseModel):
    data: list[UsageEventOut] = Field(..., title="Data")


class EnvelopeListUserOut(BaseModel):
    data: list[UserOut] = Field(..., title="Data")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class BundleV1(BaseModel):
    """
    The complete policy snapshot one data plane needs to serve requests with no database.

    Compiled by the control plane as a pure function of database state, signed, and polled
    by the data plane. If a feature seems to need a DB read on the request path, the bundle
    is missing a field; add the field here instead.
    """

    schema_version: Literal[1] = Field(1, title="Schema Version")
    bundle_id: UUID = Field(..., title="Bundle Id")
    org_id: str = Field(..., title="Org Id")
    issued_at: AwareDatetime = Field(..., title="Issued At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    keys: list[KeyEntry] = Field(..., title="Keys")
    catalog: Catalog


class SignedBundle(BaseModel):
    """
    A BundleV1 as it crosses the wire and rests on disk.

    A bundle that fails verification is rejected and the previous one keeps serving.
    """

    payload: BundleV1
    signature: str = Field(..., title="Signature")
    signing_key_id: str = Field(..., title="Signing Key Id")


class EnvelopeSignedBundle(BaseModel):
    data: SignedBundle
