# generated by datamodel-codegen:
#   filename:  airllm-openapi.json

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class ApiKey(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    allowed_models: list[str] | None = Field(None, title="Allowed Models")
    disabled: bool | None = Field(False, title="Disabled")
    created_at: AwareDatetime = Field(..., title="Created At")


class BundleOut(BaseModel):
    id: UUID = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    version: int = Field(..., title="Version")
    issued_at: AwareDatetime = Field(..., title="Issued At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    signing_key_id: str = Field(..., title="Signing Key Id")


class CompileIn(BaseModel):
    org_id: str = Field(..., description="Org to compile the bundle for", title="Org Id")


class CompileOut(BaseModel):
    bundle_id: str = Field(..., title="Bundle Id")
    version: int = Field(..., title="Version")


class HeartbeatV1(BaseModel):
    """
    A data plane announcing itself to the control plane; the record survives, liveness is derived from last_seen.
    """

    instance_id: str = Field(..., title="Instance Id")
    version: str = Field(..., title="Version")
    org_id: str | None = Field(None, title="Org Id")
    bundle_id: UUID | None = Field(None, title="Bundle Id")


class InstanceOut(BaseModel):
    instance_id: str = Field(..., title="Instance Id")
    org_id: str | None = Field(..., title="Org Id")
    version: str = Field(..., title="Version")
    bundle_id: UUID | None = Field(..., title="Bundle Id")
    address: str | None = Field(..., title="Address")
    status: Literal["online", "offline"] = Field(..., title="Status")
    first_seen: AwareDatetime = Field(..., title="First Seen")
    last_seen: AwareDatetime = Field(..., title="Last Seen")


class KeyEntry(BaseModel):
    """
    An API key as the data plane sees it: enough to authorize with zero I/O.

    Authentication is the caller's signed JWT (see tokens.py), verified against the
    signing public key; this entry is then looked up by the token's key_id claim.
    A valid signature is not enough on its own: the key must exist here, be enabled,
    and not be revoked, so revocation wins over any token still in the wild.
    """

    key_id: str = Field(..., title="Key Id")
    org_id: str = Field(..., title="Org Id")
    allowed_models: list[str] = Field(..., title="Allowed Models")
    disabled: bool | None = Field(False, title="Disabled")


class KeyIn(BaseModel):
    org_id: str = Field(..., description="Org the key belongs to", title="Org Id")
    allowed_models: list[str] | None = Field(
        ["*"],
        description="Model ids this key may call, * for all",
        title="Allowed Models",
    )


class KeyOut(BaseModel):
    key_id: str = Field(..., title="Key Id")
    token: str = Field(..., title="Token")


class KeyRevokedOut(BaseModel):
    key_id: str = Field(..., title="Key Id")
    status: Literal["revoked"] = Field(..., title="Status")


class Model(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    provider_id: str = Field(..., title="Provider Id")
    upstream_model: str = Field(..., title="Upstream Model")
    input_price_per_mtok: float = Field(..., title="Input Price Per Mtok")
    output_price_per_mtok: float = Field(..., title="Output Price Per Mtok")
    context_window: int = Field(..., title="Context Window")
    max_output_tokens: int | None = Field(None, title="Max Output Tokens")
    capabilities: list[str] | None = Field(None, title="Capabilities")


class ModelEntry(BaseModel):
    """
    A routable model: the caller-facing id plus how to reach and bill it.
    """

    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    upstream_model: str = Field(..., title="Upstream Model")
    input_price_per_mtok: float = Field(..., title="Input Price Per Mtok")
    output_price_per_mtok: float = Field(..., title="Output Price Per Mtok")
    context_window: int = Field(..., title="Context Window")
    max_output_tokens: int | None = Field(None, title="Max Output Tokens")
    capabilities: list[str] = Field(..., title="Capabilities")


class ModelIn(BaseModel):
    org_id: str = Field(..., description="Org the model belongs to", title="Org Id")
    model_id: str = Field(..., description="Caller-facing model id", title="Model Id")
    provider_id: str = Field(..., description="Provider id the model routes to", title="Provider Id")
    upstream_model: str | None = Field(
        "",
        description="Model name sent to the provider, lets model_id be an alias; defaults to model_id",
        title="Upstream Model",
    )
    input_price_per_mtok: float | None = Field(0.0, description="USD per million input tokens", title="Input Price Per Mtok")
    output_price_per_mtok: float | None = Field(0.0, description="USD per million output tokens", title="Output Price Per Mtok")
    context_window: int | None = Field(128000, description="Context window in tokens", title="Context Window")
    max_output_tokens: int | None = Field(
        None,
        description="Max completion tokens; requests are clamped to it",
        title="Max Output Tokens",
    )
    capabilities: list[str] | None = Field(
        ["streaming", "tools"],
        description="Capabilities, comma separated",
        title="Capabilities",
    )


class ModelOut(BaseModel):
    model_id: str = Field(..., title="Model Id")


class Org(BaseModel):
    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    created_at: AwareDatetime = Field(..., title="Created At")


class OrgIn(BaseModel):
    id: str = Field(..., description="Org id, e.g. org-dev", title="Id")
    name: str | None = Field("", description="Display name, defaults to the id", title="Name")


class OrgOut(BaseModel):
    id: str = Field(..., title="Id")


class Provider(BaseModel):
    id: str = Field(..., title="Id")
    org_id: str = Field(..., title="Org Id")
    kind: str = Field(..., title="Kind")
    base_url: str = Field(..., title="Base Url")
    credential_ref: str = Field(..., title="Credential Ref")
    cache_read_multiplier: float | None = Field(1.0, title="Cache Read Multiplier")
    cache_write_multiplier: float | None = Field(1.0, title="Cache Write Multiplier")


class ProviderEntry(BaseModel):
    """
    An upstream LLM provider endpoint.
    """

    provider_id: str = Field(..., title="Provider Id")
    kind: Literal["openai_compatible", "anthropic"] = Field(..., title="Kind")
    base_url: AnyUrl = Field(..., title="Base Url")
    credential_ref: str = Field(..., title="Credential Ref")
    cache_read_multiplier: float | None = Field(1.0, title="Cache Read Multiplier")
    cache_write_multiplier: float | None = Field(1.0, title="Cache Write Multiplier")


class ProviderIn(BaseModel):
    org_id: str = Field(..., description="Org the provider belongs to", title="Org Id")
    provider_id: str = Field(..., description="Provider id, e.g. openai", title="Provider Id")
    kind: Literal["openai_compatible", "anthropic"] | None = Field("openai_compatible", description="Adapter kind", title="Kind")
    base_url: str = Field(
        ...,
        description="OpenAI-compatible endpoint, e.g. https://api.groq.com/openai/v1",
        title="Base Url",
    )
    credential_ref: str = Field(
        ...,
        description="env: or file: reference resolved by the data plane, never a raw secret",
        title="Credential Ref",
    )
    cache_read_multiplier: float | None = Field(
        1.0,
        description="Input price factor for prompt-cache hits",
        title="Cache Read Multiplier",
    )
    cache_write_multiplier: float | None = Field(
        1.0,
        description="Input price factor for cache writes",
        title="Cache Write Multiplier",
    )


class ProviderOut(BaseModel):
    provider_id: str = Field(..., title="Provider Id")


class UsageEvent(BaseModel):
    event_id: UUID = Field(..., title="Event Id")
    request_id: str = Field(..., title="Request Id")
    occurred_at: AwareDatetime = Field(..., title="Occurred At")
    org_id: str = Field(..., title="Org Id")
    key_id: str = Field(..., title="Key Id")
    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    bundle_id: UUID = Field(..., title="Bundle Id")
    input_tokens: int = Field(..., title="Input Tokens")
    output_tokens: int = Field(..., title="Output Tokens")
    cost_usd: float = Field(..., title="Cost Usd")
    cost_input_usd: float | None = Field(0.0, title="Cost Input Usd")
    cost_output_usd: float | None = Field(0.0, title="Cost Output Usd")
    cache_read_tokens: int | None = Field(0, title="Cache Read Tokens")
    cache_write_tokens: int | None = Field(0, title="Cache Write Tokens")
    latency_ms: int = Field(..., title="Latency Ms")
    status: str = Field(..., title="Status")
    stream: bool = Field(..., title="Stream")


class UsageEventV1(BaseModel):
    """
    One metered request, emitted by the data plane and ingested by the control plane.

    Delivery is at-least-once from a local disk buffer; the control plane upserts on
    event_id, so replays after an outage land exactly once.
    """

    schema_version: Literal[1] = Field(1, title="Schema Version")
    event_id: UUID = Field(..., title="Event Id")
    request_id: str = Field(..., title="Request Id")
    occurred_at: AwareDatetime = Field(..., title="Occurred At")
    org_id: str = Field(..., title="Org Id")
    key_id: str = Field(..., title="Key Id")
    model_id: str = Field(..., title="Model Id")
    provider_id: str = Field(..., title="Provider Id")
    bundle_id: UUID = Field(..., title="Bundle Id")
    input_tokens: int = Field(..., title="Input Tokens")
    output_tokens: int = Field(..., title="Output Tokens")
    cost_usd: float = Field(..., title="Cost Usd")
    cost_input_usd: float | None = Field(0.0, title="Cost Input Usd")
    cost_output_usd: float | None = Field(0.0, title="Cost Output Usd")
    cache_read_tokens: int | None = Field(0, title="Cache Read Tokens")
    cache_write_tokens: int | None = Field(0, title="Cache Write Tokens")
    latency_ms: int = Field(..., title="Latency Ms")
    status: Literal["ok", "upstream_error", "denied", "timeout", "cancelled"] = Field(..., title="Status")
    stream: bool = Field(..., title="Stream")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class Catalog(BaseModel):
    """
    Everything routable in one org: providers and the models that point at them.
    """

    providers: list[ProviderEntry] = Field(..., title="Providers")
    models: list[ModelEntry] = Field(..., title="Models")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class BundleV1(BaseModel):
    """
    The complete policy snapshot one data plane needs to serve requests with no database.

    Compiled by the control plane as a pure function of database state, signed, and polled
    by the data plane. If a feature seems to need a DB read on the request path, the bundle
    is missing a field; add the field here instead.
    """

    schema_version: Literal[1] = Field(1, title="Schema Version")
    bundle_id: UUID = Field(..., title="Bundle Id")
    org_id: str = Field(..., title="Org Id")
    issued_at: AwareDatetime = Field(..., title="Issued At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    keys: list[KeyEntry] = Field(..., title="Keys")
    revocations: list[str] = Field(..., title="Revocations")
    catalog: Catalog


class SignedBundle(BaseModel):
    """
    A BundleV1 as it crosses the wire and rests on disk.

    A bundle that fails verification is rejected and the previous one keeps serving.
    """

    payload: BundleV1
    signature: str = Field(..., title="Signature")
    signing_key_id: str = Field(..., title="Signing Key Id")
