"""dataplane instance fields

Revision ID: 5fcd0d00191c
Revises: 8148167124b2
Create Date: 2026-08-04 12:43:58.569015
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = "5fcd0d00191c"
down_revision = "8148167124b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataplaneinstance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("first_seen", sa.DateTime(), nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataplaneinstance", schema=None) as batch_op:
        batch_op.drop_column("first_seen")
        batch_op.drop_column("address")
        batch_op.drop_column("org_id")

    # ### end Alembic commands ###
