"""provider cache multipliers

Revision ID: 8148167124b2
Revises: 9ec6087d0cda
Create Date: 2026-08-04 00:40:13.363657
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = "8148167124b2"
down_revision = "9ec6087d0cda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cache_read_multiplier", sa.Float(), nullable=False, server_default="1.0"))
        batch_op.add_column(sa.Column("cache_write_multiplier", sa.Float(), nullable=False, server_default="1.0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.drop_column("cache_write_multiplier")
        batch_op.drop_column("cache_read_multiplier")

    # ### end Alembic commands ###
