"""model max_output_tokens

Revision ID: 8e3abb84c2d2
Revises: fc544cfa4524
Create Date: 2026-08-04 00:13:22.145450
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = "8e3abb84c2d2"
down_revision = "fc544cfa4524"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_output_tokens", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.drop_column("max_output_tokens")

    # ### end Alembic commands ###
