"""event cache tokens

Revision ID: 9ec6087d0cda
Revises: 8e3abb84c2d2
Create Date: 2026-08-04 00:31:36.055438
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = "9ec6087d0cda"
down_revision = "8e3abb84c2d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usageevent", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cache_read_tokens", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("cache_write_tokens", sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usageevent", schema=None) as batch_op:
        batch_op.drop_column("cache_write_tokens")
        batch_op.drop_column("cache_read_tokens")

    # ### end Alembic commands ###
