"""event cost breakdown

Revision ID: fc544cfa4524
Revises: e9f8634c389b
Create Date: 2026-08-03 21:34:05.390509
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = "fc544cfa4524"
down_revision = "e9f8634c389b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usageevent", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cost_input_usd", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("cost_output_usd", sa.Float(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usageevent", schema=None) as batch_op:
        batch_op.drop_column("cost_output_usd")
        batch_op.drop_column("cost_input_usd")

    # ### end Alembic commands ###
